// Generated by rune manifest from spec/runes/notes.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Id } from "./mod.ts";

Deno.test("Id.generate", () => {
  // Arrange — (static) Id.generate
  // Act — generate(): id
  // Assert — TODO: assert the id result
});
