// Generated by shape-checker manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Coordinator for [REQ] order.place(PlaceOrderDto): ReceiptDto.

export async function place(input: PlaceOrderDto): Promise<ReceiptDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
