// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { CheckoutDto } from "@/src/cake/dto/checkout.ts";
import type { ReceiptDto } from "@/src/cake/dto/receipt.ts";
import { Receipt } from "@/src/cake/domain/business/receipt/mod.ts";

// Coordinator for [REQ] receipt.pay(CheckoutDto): ReceiptDto.
export async function pay(input: CheckoutDto): Promise<ReceiptDto> {

  // core — pure business logic, no I/O
  const out = payCore(input);

  return out.result;
}

// Pure business logic for receipt.pay — no I/O. Takes the
// request input; returns the result.
function payCore(input: CheckoutDto): { result: ReceiptDto } {
  const receipt = new Receipt();
  return { result: { ingredientsId: `ing-${input.cartId}` } };
}
