// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Polymorphic base for "Channel". Variants extend this.

export abstract class ChannelBase {
  abstract deliver(sendDto: unknown): unknown;
}
