// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Task } from "./mod.ts";

Deno.test("Task.fill", () => {
  // TODO: test fill
});

Deno.test("Task.save", () => {
  // TODO: test save
});

Deno.test("Task.toDto", () => {
  // TODO: test toDto
});

Deno.test("Task.load", () => {
  // TODO: test load
});

Deno.test("Task.markDone", () => {
  // TODO: test markDone
});
