// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the notification body text
// rune declares: [TYP] message: string
export const messageSchema = z.unknown(); // TODO: tighten to string
export type message = z.infer<typeof messageSchema>;
