// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// proof that a notification was delivered
export class ReceiptDto {
  @IsString()
  id!: string;

  @IsString()
  status!: string;
}
