// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// proof that a notification was delivered
export const ReceiptDtoSchema = z.object({

  id: z.unknown(), // TODO: tighten

  status: z.unknown(), // TODO: tighten

});

export type ReceiptDto = z.infer<typeof ReceiptDtoSchema>;
