// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// input to send a notification
export const SendDtoSchema = z.object({

  message: z.unknown(), // TODO: tighten

});

export type SendDto = z.infer<typeof SendDtoSchema>;
