// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// whether the task has been completed
// rune declares: [TYP] done: boolean
export type Done = boolean;
