// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a unique task identifier
// rune declares: [TYP] id: string
export type Id = string;
