// Generated by rune sync — DO NOT EDIT.
// Module registry: one entry per rune surface, regenerated on every sync as
// runes are added and removed. bootstrap/mod.ts (dev-owned) wires it to keep.

import { httpModule as mediaHttpModule } from "@/src/media/entrypoints/http/mod.ts";
import { wsModule as mediaWsModule } from "@/src/media/entrypoints/ws/mod.ts";
import { checkModule as runeCheckModule } from "@/src/rune/entrypoints/check/mod.ts";
import { devModule as runeDevModule } from "@/src/rune/entrypoints/dev/mod.ts";
import { manifestModule as runeManifestModule } from "@/src/rune/entrypoints/manifest/mod.ts";
import { syncModule as runeSyncModule } from "@/src/rune/entrypoints/sync/mod.ts";
import { updateModule as runeUpdateModule } from "@/src/rune/entrypoints/update/mod.ts";
import { validateModule as runeValidateModule } from "@/src/rune/entrypoints/validate/mod.ts";

export const modules = [
  mediaHttpModule,
  mediaWsModule,
  runeCheckModule,
  runeDevModule,
  runeManifestModule,
  runeSyncModule,
  runeUpdateModule,
  runeValidateModule,
];
