// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { MixDto } from "@/src/cake/dto/mix.ts";
import type { BatterDto } from "@/src/cake/dto/batter.ts";
import { Batter } from "@/src/cake/domain/business/batter/mod.ts";

// Coordinator for [REQ] batter.mix(MixDto): BatterDto.
export async function mix(input: MixDto): Promise<BatterDto> {

  // core — pure business logic, no I/O
  const out = mixCore(input);

  return out.result;
}

// Pure business logic for batter.mix — no I/O. Takes the
// request input; returns the result.
function mixCore(input: MixDto): { result: BatterDto } {
  const batter = new Batter();
  return { result: { batterId: `batter-${input.ingredientsId}` } };
}
