// Generated by rune manifest from spec/runes/tasks.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

export class Id {
  static generate(): string {
    return crypto.randomUUID();
  }
}
