// Generated by rune manifest from spec/runes/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { assert, assertEquals, assertNotEquals } from "#std/assert";
import { Id } from "./mod.ts";

Deno.test("Id.generate", () => {
  // Arrange — static pure method, no setup needed

  // Act
  const id1 = Id.generate();
  const id2 = Id.generate();

  // Assert — result must be a non-empty string
  assertEquals(typeof id1, "string");
  assert(id1.length > 0, "generated id must be non-empty");

  // Assert — two successive calls must yield distinct identifiers
  assertNotEquals(id1, id2, "successive Id.generate() calls must yield distinct ids");
});
