// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import ChannelPush from "./mod.ts";

Deno.test("Channel/Push — placeholder", () => {
  // TODO: variant-specific tests
});
