// Generated by rune manifest from corpus/valid/module-billing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Recipe (from [REQ] invoice.issue @ corpus/valid/module-billing.rune:3):
//   1. [RET] InvoiceDto

import { issue } from "./mod.ts";

Deno.test("issue — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

