// Generated by rune manifest from corpus/valid/module-billing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IssueDto } from "@/src/billing/dto/issue.ts";
import { InvoiceDto } from "@/src/billing/dto/invoice.ts";
import { assert } from "#assert";
import { Invoice } from "@/src/billing/domain/business/invoice/mod.ts";
import { Invoice as InvoiceData } from "@/src/billing/domain/data/invoice/mod.ts";

// Coordinator for [REQ] invoice.issue(IssueDto): InvoiceDto.
export async function issue(input: IssueDto): Promise<InvoiceDto> {
  const validInput = assert(IssueDto, input, "invoice.issue input");
  const invoiceData = new InvoiceData();

  // reads — load inputs through the data adapters (validated at the seam)
  const invoiceSave = assert(InvoiceDto, await invoiceData.save(undefined as never), "invoice.save");

  // core — pure business logic, no I/O
  const out = issueCore(validInput, invoiceSave);

  return assert(InvoiceDto, out.result, "invoice.issue output");
}

// Pure business logic for invoice.issue — no I/O. Takes the
// request input and the dtos the reads loaded; returns the result.
function issueCore(input: IssueDto, invoiceSave: InvoiceDto): { result: InvoiceDto } {
  const invoice = new Invoice();
  // TODO: run the pure steps on invoice, build the dtos
  throw new Error("not implemented");
}
