// Generated by rune manifest from corpus/valid/module-billing.rune:3.
// Edit the body. Re-running manifest will not overwrite this file.

import { IssueDto } from "@/src/billing/dto/issue.ts";
import { InvoiceDto } from "@/src/billing/dto/invoice.ts";
import { assert } from "#assert";
import { Invoice as InvoiceData } from "@/src/billing/domain/data/invoice/mod.ts";

/**
 * Coordinator for [REQ] invoice.issue(IssueDto): InvoiceDto.
 * @param input IssueDto — asserted against its contract at the seam.
 * @returns InvoiceDto — asserted before return.
 * @throws timeout — raised by invoice.save
 */
export async function issue(input: IssueDto): Promise<InvoiceDto> {
  const validInput = assert(IssueDto, input, "invoice.issue input");
  const invoiceData = new InvoiceData();

  // core — pure business logic, no I/O
  issueCore(validInput);

  // after the core — boundary calls in spec order (validated at the seam)
  // (guards run in the core above: a throw there prevents every call below)
  const invoiceSave = assert(InvoiceDto, await invoiceData.save(validInput), "invoice.save");

  return invoiceSave;
}

// Pure business logic for invoice.issue — no I/O. Takes the
// request input; returns nothing (the post-core boundary calls produce the flow's values).
function issueCore(input: IssueDto): void {
  // Recipe from [REQ] invoice.issue (run in order):
  //   1. [RET] InvoiceDto
  // TODO: implement the steps above, then build the dtos
  throw new Error("not implemented");
}
