// Generated by shape-checker manifest from corpus/valid/module-billing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Coordinator for [REQ] invoice.issue(IssueDto): InvoiceDto.

export async function issue(input: IssueDto): Promise<InvoiceDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
