// Ghost stubs: find the [TYP:ext] inputs no module in the project produces and
// render bootstrap/stubs.ts — a keep module with one trivial GET endpoint per
// unfulfilled input that mints placeholder values. It mounts like any module
// (emulator at /docs/stubs), is excluded in production by the registry's gate,
// and evaporates when a later-synced module produces the field. Pure: no I/O —
// the sync entrypoint decides where to write or delete.

import { parse } from "@rune/domain/business/rune-parse/mod.ts";
import { dtoFieldNames } from "@rune/domain/business/rune-manifest/mod.ts";
import { applyCase } from "@rune/domain/business/rune-bindings/mod.ts";

/** One unfulfilled external input: the [TYP:ext] name and its declared primitive. */
export interface StubField {
  name: string; // "memberId"
  tsType: string; // the [TYP] primitive: "string" | "number" | "boolean" | …
}

/**
 * Plan the ghost stub fields across every project spec:
 * (a) each [TYP:ext] name some module's ENT input DTO consumes with no producer
 *     in its own module (mirrors computeEntProcess — exactly the `$name` binds
 *     the generated controllers carry), minus
 * (b) the union of ALL modules' ENT output-DTO field names (a producer anywhere
 *     in the project fulfills the contract — no stub needed).
 * Specs with parse errors contribute nothing (sync reports them elsewhere).
 */
export function planStubs(
  specs: { path: string; text: string }[],
): StubField[] {
  const wanted = new Map<string, string>(); // ext name → typeName (first declaration wins)
  const producedAnywhere = new Set<string>();
  for (const spec of specs) {
    const ast = parse(spec.text);
    if (ast.errors.length > 0) continue;
    const dtoByName = new Map(ast.dtos.map((d) => [d.name, d]));
    const externalTypes = new Map(
      ast.typs.filter((t) => t.isExternal).map((t) => [t.name, t.typeName]),
    );
    const outputFields = (entOutput: string): string[] => {
      const dto = dtoByName.get(entOutput);
      return dto ? dtoFieldNames(dto) : [];
    };
    for (const ent of ast.ents) {
      for (const f of outputFields(ent.output)) producedAnywhere.add(f);
    }
    for (const ent of ast.ents) {
      const inDto = dtoByName.get(ent.input);
      if (!inDto) continue;
      for (const field of dtoFieldNames(inDto)) {
        // Mirror computeEntProcess: a field is unproduced when no OTHER ent in
        // the same module outputs it; only then does its ext [TYP] make it a
        // `$field` bind — and a stub candidate.
        const produced = ast.ents.some(
          (p) => p !== ent && outputFields(p.output).includes(field),
        );
        if (produced) continue;
        const typeName = externalTypes.get(field);
        if (typeName !== undefined && !wanted.has(field)) {
          wanted.set(field, typeName);
        }
      }
    }
  }
  return [...wanted]
    .filter(([name]) => !producedAnywhere.has(name))
    .map(([name, tsType]) => ({ name, tsType }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

// camelCase/kebab/snake → PascalCase ("memberId" → "MemberId", "member-id" → "MemberId").
function pascal(name: string): string {
  const camel = name.replace(/[-_](\w)/g, (_, c: string) => c.toUpperCase());
  return applyCase(camel, "pascal");
}

// The placeholder a stub mints, by the field's declared primitive. Strings get a
// counter suffix (module-level, so re-runs mint fresh ids); unknown types mint
// strings too — the safest stand-in.
function mintFor(field: StubField): { ts: string; expr: string; dec: string } {
  switch (field.tsType) {
    case "number":
      return { ts: "number", expr: "counter++", dec: "IsNumber" };
    case "boolean":
      return { ts: "boolean", expr: "true", dec: "IsBoolean" };
    default:
      return {
        ts: "string",
        expr: `"stub-${field.name}-" + counter++`,
        dec: "IsString",
      };
  }
}

/**
 * Render bootstrap/stubs.ts. The header line is the delete-guard: sync only
 * removes the file when it starts with it. Imports ONLY keep + class-validator
 * (the validator decorators emit `design:type`, which is all the schema builder
 * needs) — no danet/swagger imports. The production gate is NOT here; it lives
 * in bootstrap/modules.ts.
 */
export function renderStubsModule(fields: StubField[]): string {
  const mints = fields.map((f) => ({ field: f, mint: mintFor(f) }));
  const validators = [...new Set(mints.map((m) => m.mint.dec))].sort();
  const needsCounter = mints.some((m) => m.mint.expr.includes("counter"));

  const L: string[] = [
    "// Generated by rune sync — DO NOT EDIT.",
    "// Ghost stub module: one GET endpoint per [TYP:ext] input nothing in the",
    "// project produces yet. Each endpoint mints a placeholder value so dependent",
    "// modules run end-to-end before their real producers exist. This file",
    "// evaporates when a synced module produces the field; bootstrap/modules.ts",
    "// excludes it in production. Business code never references it.",
    "",
    'import { Endpoint, EndpointController, endpointModule } from "@mrg-keystone/keep";',
    `import { ${validators.join(", ")} } from "class-validator";`,
    "",
  ];
  if (needsCounter) {
    L.push("// Module-level counter: re-runs mint fresh values, never colliding captures.");
    L.push("let counter = 1;");
    L.push("");
  }
  for (const { field, mint } of mints) {
    L.push(`// stand-in output for ${field.name}`);
    L.push(`class ${pascal(field.name)}StubDto {`);
    L.push(`  @${mint.dec}()`);
    L.push(`  ${field.name}!: ${mint.ts};`);
    L.push("}");
    L.push("");
  }
  L.push('@EndpointController("stubs")');
  L.push("class StubsController {");
  mints.forEach(({ field, mint }, i) => {
    if (i > 0) L.push("");
    const dto = `${pascal(field.name)}StubDto`;
    L.push(
      `  @Endpoint({ method: "get", path: "mint-${
        applyCase(field.name, "kebab")
      }", output: ${dto}, stub: true, description: "stand-in for the unbuilt producer of ${field.name}" })`,
    );
    L.push(`  mint${pascal(field.name)}(): ${dto} {`);
    L.push(`    const dto = new ${dto}();`);
    L.push(`    dto.${field.name} = ${mint.expr};`);
    L.push("    return dto;");
    L.push("  }");
  });
  L.push("}");
  L.push("");
  L.push('export const stubsModule = endpointModule("Stubs", [StubsController]);');
  L.push("");
  return L.join("\n");
}
