import { assertEquals, assertStringIncludes } from "#std/assert";
import { planInputDiagnostics, planStubs, renderStubsModule } from "./mod.ts";

// A module whose ENT consumes an ext field nothing in the module produces.
const CHECKOUT = `[MOD] checkout

[ENT] http.start(StartDto): TicketDto

[DTO] StartDto: item, memberId
    what to buy and who buys it
[DTO] TicketDto: ticketId
    the opened ticket

[TYP:ext] memberId: string
    minted by the members module
[TYP] item: string
    a thing to buy
[TYP] ticketId: string
    a ticket id`;

// A module whose ENT OUTPUT produces memberId — the real producer.
const MEMBERS = `[MOD] members

[ENT] http.join(JoinDto): MemberDto

[DTO] JoinDto: alias
    who joins
[DTO] MemberDto: memberId
    the minted member

[TYP] alias: string
    a display name
[TYP] memberId: string
    a member id`;

Deno.test("planStubs — unfulfilled [TYP:ext] input is planned", () => {
  const fields = planStubs([{ path: "src/checkout/checkout.rune", text: CHECKOUT }]);
  assertEquals(fields, [{ name: "memberId", tsType: "string" }]);
});

Deno.test("planStubs — input produced by ANOTHER module's ENT output is not planned", () => {
  const fields = planStubs([
    { path: "src/checkout/checkout.rune", text: CHECKOUT },
    { path: "src/members/members.rune", text: MEMBERS },
  ]);
  assertEquals(fields, []);
});

Deno.test("planStubs — input produced within its own module is not planned", () => {
  const spec = `[MOD] shop

[ENT] http.mint(MintDto): IdDto
[ENT] http.use(UseDto): DoneDto

[DTO] MintDto: seed
    a seed
[DTO] IdDto: memberId
    the id
[DTO] UseDto: memberId
    the id to use
[DTO] DoneDto: done
    confirmation

[TYP] seed: string
    a seed
[TYP:ext] memberId: string
    declared ext, but minted locally
[TYP] done: boolean
    flag`;
  assertEquals(planStubs([{ path: "src/shop/shop.rune", text: spec }]), []);
});

Deno.test("planStubs — multi-module union, deduped and sorted, with type mapping", () => {
  const a = `[MOD] alpha

[ENT] http.go(GoDto): OutDto

[DTO] GoDto: zCode, memberId
    inputs
[DTO] OutDto: result
    output

[TYP:ext] zCode: number
    external code
[TYP:ext] memberId: string
    external id
[TYP] result: string
    output value`;
  const b = `[MOD] beta

[ENT] http.run(RunDto): ResDto

[DTO] RunDto: aFlag, memberId
    inputs
[DTO] ResDto: outcome
    output

[TYP:ext] aFlag: boolean
    external flag
[TYP:ext] memberId: string
    external id (same as alpha's — deduped)
[TYP] outcome: string
    output value`;
  const fields = planStubs([
    { path: "src/alpha/alpha.rune", text: a },
    { path: "src/beta/beta.rune", text: b },
  ]);
  assertEquals(fields, [
    { name: "aFlag", tsType: "boolean" },
    { name: "memberId", tsType: "string" },
    { name: "zCode", tsType: "number" },
  ]);
});

Deno.test("planStubs — a spec with parse errors contributes nothing", () => {
  const broken = `[MOD] broken

[ENT] not-a-signature

[TYP:ext] ghostField: string
    never planned — the spec is broken`;
  assertEquals(planStubs([{ path: "src/broken/broken.rune", text: broken }]), []);
  // …and it doesn't poison other specs either.
  const fields = planStubs([
    { path: "src/broken/broken.rune", text: broken },
    { path: "src/checkout/checkout.rune", text: CHECKOUT },
  ]);
  assertEquals(fields, [{ name: "memberId", tsType: "string" }]);
});

Deno.test("renderStubsModule — header, stub flag, mint endpoint, types", () => {
  const out = renderStubsModule([
    { name: "aFlag", tsType: "boolean" },
    { name: "memberId", tsType: "string" },
    { name: "zCode", tsType: "number" },
  ]);
  // The header line is the delete-guard.
  assertEquals(out.startsWith("// Generated by rune sync — DO NOT EDIT.\n"), true);
  // Imports: keep + class-validator only.
  assertStringIncludes(
    out,
    'import { Endpoint, EndpointController, endpointModule } from "@mrg-keystone/rune";',
  );
  assertStringIncludes(out, 'import { IsBoolean, IsNumber, IsString } from "class-validator";');
  assertEquals(out.includes("danet"), false);
  // One mint endpoint per field, marked as a stub.
  assertStringIncludes(
    out,
    '@Endpoint({ method: "get", path: "mint-member-id", output: MemberIdStubDto, stub: true, description: "stand-in for the unbuilt producer of memberId" })',
  );
  assertStringIncludes(out, "mintMemberId(): MemberIdStubDto {");
  assertStringIncludes(out, 'dto.memberId = "stub-memberId-" + counter++;');
  assertStringIncludes(out, 'path: "mint-z-code"');
  assertStringIncludes(out, "dto.zCode = counter++;");
  assertStringIncludes(out, 'path: "mint-a-flag"');
  assertStringIncludes(out, "dto.aFlag = true;");
  // DTO fields carry the declared primitive + its validator.
  assertStringIncludes(out, "@IsBoolean()\n  aFlag!: boolean;");
  assertStringIncludes(out, "@IsNumber()\n  zCode!: number;");
  assertStringIncludes(out, "@IsString()\n  memberId!: string;");
  // The module export the registry imports.
  assertStringIncludes(out, 'export const stubsModule = endpointModule("Stubs", [StubsController]);');
  // The production gate is NOT here — it lives in bootstrap/modules.ts.
  assertEquals(out.includes("DENO_ENV"), false);
});

Deno.test("renderStubsModule — boolean-only fields emit no counter", () => {
  const out = renderStubsModule([{ name: "ready", tsType: "boolean" }]);
  assertEquals(out.includes("counter"), false);
  assertStringIncludes(out, "dto.ready = true;");
});

// A producer whose OUTPUT is the plural collection (tableNames) of the field a
// consumer needs ($tableName) — keep's contract resolves it, so no stub.
const DISCOVER = `[MOD] catalog

[ENT] http.discover(DiscoverDto): CatalogDto

[DTO] DiscoverDto: realm
    where to look
[DTO] CatalogDto: tableName(s)
    every discovered table

[TYP:example=acme] realm: string
    x
[TYP] tableName: string
    x`;

const CONSUMER = `[MOD] writes

[ENT] http.write(WriteDto): RowDto

[DTO] WriteDto: tableName
    a row to write
[DTO] RowDto: rowId
    the written row

[TYP:ext] tableName: string
    discovered elsewhere
[TYP] rowId: string
    x`;

Deno.test("planStubs — a plural collection output fulfills the singular $input (no stub)", () => {
  const fields = planStubs([
    { path: "src/catalog/catalog.rune", text: DISCOVER },
    { path: "src/writes/writes.rune", text: CONSUMER },
  ]);
  assertEquals(fields, []);
});

Deno.test("planStubs — without the plural producer the stub is still planned", () => {
  const fields = planStubs([{ path: "src/writes/writes.rune", text: CONSUMER }]);
  assertEquals(fields, [{ name: "tableName", tsType: "string" }]);
});

Deno.test("planInputDiagnostics — $input with no exact/plural producer names near-misses", () => {
  // The producer outputs `tables` — NOT `tableName` or `tableNames` — a
  // near-miss that silently fails the plural convention.
  const nearMiss = DISCOVER.replace("tableName(s)", "table(s)").replace(
    "[TYP] tableName: string",
    "[TYP] table: string",
  );
  const notes = planInputDiagnostics([
    { path: "src/catalog/catalog.rune", text: nearMiss },
    { path: "src/writes/writes.rune", text: CONSUMER },
  ]);
  assertEquals(notes.length, 1);
  assertEquals(notes[0].includes("$tableName"), true);
  assertEquals(notes[0].includes("ghost stub"), true);
});

Deno.test("planInputDiagnostics — fulfilled by the plural producer → no notes", () => {
  const notes = planInputDiagnostics([
    { path: "src/catalog/catalog.rune", text: DISCOVER },
    { path: "src/writes/writes.rune", text: CONSUMER },
  ]);
  assertEquals(notes, []);
});

Deno.test("planInputDiagnostics — unwired field with no example is a guaranteed-422 warning", () => {
  // `realm` has no producer, no ext, no example.
  const noExample = DISCOVER.replace("[TYP:example=acme] realm", "[TYP] realm");
  const notes = planInputDiagnostics([
    { path: "src/catalog/catalog.rune", text: noExample },
  ]);
  assertEquals(notes.length, 1);
  assertEquals(notes[0].includes('field "realm"'), true);
  assertEquals(notes[0].includes("guaranteed 422"), true);
});

Deno.test("planInputDiagnostics — an example silences the 422 warning", () => {
  const notes = planInputDiagnostics([
    { path: "src/catalog/catalog.rune", text: DISCOVER },
  ]);
  assertEquals(notes, []);
});

// ---- S4: a field name that is not a valid TS identifier must not produce
//      uncompilable code (e.g. `class 3dModelStubDto`, `dto.3dModel = …`). ----
Deno.test("renderStubsModule — S4: a leading-digit field name yields compilable TS", async () => {
  const out = renderStubsModule([{ name: "3dModel", tsType: "string" }]);
  // The class/method identifiers must be valid TS — a leading digit is illegal.
  assertEquals(
    out.includes("class 3dModelStubDto"),
    false,
    "class identifier must be sanitized, not start with a digit",
  );
  assertEquals(
    out.includes("mint3dModel("),
    false,
    "method identifier must be sanitized",
  );
  // The field name itself must stay literally `3dModel` (keep binds `$3dModel`
  // to the field of that exact name) — so it must be QUOTED, never a bare ident.
  assertEquals(
    /\n  3dModel!:/.test(out),
    false,
    "a non-identifier property must be quoted, not bare",
  );
  assertEquals(
    out.includes("dto.3dModel ="),
    false,
    "a non-identifier property access must be bracketed, not dotted",
  );
  // Ground truth: the output must actually type-check.
  const dir = await Deno.makeTempDir();
  const file = `${dir}/stubs_gen.ts`;
  // Drop the keep import (not resolvable here) — we only check identifier/syntax
  // validity of the generated DTO + handler shapes.
  const stripped = out.replace(
    /import \{ Endpoint, EndpointController, endpointModule \} from "@mrg-keystone\/rune";/,
    "const Endpoint = (_: unknown) => (_t: unknown, _k?: unknown) => {};\nconst EndpointController = (_: unknown) => (_t: unknown) => {};\nconst endpointModule = (_: unknown, __: unknown) => ({});",
  );
  await Deno.writeTextFile(file, stripped);
  const cmd = new Deno.Command(Deno.execPath(), {
    args: ["check", file],
    stderr: "piped",
    stdout: "piped",
  });
  const { code, stderr } = await cmd.output();
  await Deno.remove(dir, { recursive: true });
  assertEquals(
    code,
    0,
    `generated stubs.ts must type-check; got:\n${new TextDecoder().decode(stderr)}`,
  );
});

// ---- S8: two modules declaring the SAME [TYP:ext] field with DIFFERENT
//      primitives must not be silently resolved by file order. ----
const S8_ALPHA = `[MOD] alpha

[ENT] http.a(AInDto): AOutDto

[DTO] AInDto: amount
    x
[DTO] AOutDto: aId
    x

[TYP:ext] amount: number
    a numeric amount
[TYP] aId: string
    x`;

const S8_BETA = `[MOD] beta

[ENT] http.b(BInDto): BOutDto

[DTO] BInDto: amount
    x
[DTO] BOutDto: bId
    x

[TYP:ext] amount: string
    a string amount
[TYP] bId: string
    x`;

Deno.test("planStubs — S8: a conflicting cross-module [TYP:ext] type is order-independent", () => {
  const ab = planStubs([
    { path: "src/alpha/alpha.rune", text: S8_ALPHA },
    { path: "src/beta/beta.rune", text: S8_BETA },
  ]);
  const ba = planStubs([
    { path: "src/beta/beta.rune", text: S8_BETA },
    { path: "src/alpha/alpha.rune", text: S8_ALPHA },
  ]);
  // The stub result must NOT silently flip with input order. Either the field is
  // diagnosed/dropped, or it is resolved deterministically regardless of order —
  // never "whichever spec was processed first wins".
  assertEquals(
    JSON.stringify(ab),
    JSON.stringify(ba),
    "a conflicting ext-type must not depend on spec/path order",
  );
});

Deno.test("planInputDiagnostics — S8: conflicting cross-module ext type is reported", () => {
  const notes = planInputDiagnostics([
    { path: "src/alpha/alpha.rune", text: S8_ALPHA },
    { path: "src/beta/beta.rune", text: S8_BETA },
  ]);
  assertEquals(
    notes.some((n) =>
      n.includes("amount") && /conflict|differ|mismatch|number|string/i.test(n)
    ),
    true,
    `expected a conflicting-type diagnostic for amount, got: ${
      JSON.stringify(notes)
    }`,
  );
});
