// Generated by rune manifest — DO NOT EDIT (regenerated on every `rune sync`).

// Domain nouns (from [NON]):
//   note: a single note
//
// Type vocabulary (from [TYP]):
//   id: string — a unique note identifier
//   body: string — the note body text
//   archived: boolean — whether the note has been archived
//
// Backing services (shared, from src/core/core.rune):
//   db (SIDECAR): DB_URL
// Public API surface for module "notes".

export { create } from "./domain/coordinators/note-create/mod.ts";

export { archive } from "./domain/coordinators/note-archive/mod.ts";

