// Generated by rune manifest from spec/runes/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { create } from "./mod.ts";
import { CreateTaskDto } from "@/src/tasks/dto/create-task.ts";
import { DbService } from "@/src/core/data/db/mod.ts";
import { assertEquals, assertRejects } from "#std/assert";

function createInput(title: string): CreateTaskDto {
  return Object.assign(new CreateTaskDto(), { title });
}

// Happy path: the shell wires id::generate → fill(title) → save → toDto, and
// returns a persisted TaskDto with a fresh id, the given title, and done=false.
Deno.test("create — happy path", async () => {
  const result = await create(createInput("write the eval"));
  assertEquals(result.title, "write the eval");
  assertEquals(result.done, false);
  assertEquals(typeof result.id, "string");
  assertEquals(result.id.length > 0, true);
});

// The `timeout` fault from the db save boundary propagates out of create().
Deno.test("timeout", async () => {
  DbService.failNextPut = "timeout";
  await assertRejects(() => create(createInput("x")), Error, "timeout");
});
