// Generated by rune manifest from spec/runes/tasks.rune:3.
// Edit the body. Re-running manifest will not overwrite this file.

import { CreateTaskDto } from "@/src/tasks/dto/create-task.ts";
import { TaskDto } from "@/src/tasks/dto/task.ts";
import { assert } from "#assert";
import { Id } from "@/src/tasks/domain/business/id/mod.ts";
import { Task } from "@/src/tasks/domain/business/task/mod.ts";
import { Task as TaskData } from "@/src/tasks/domain/data/task/mod.ts";

/**
 * Coordinator for [REQ] task.create(CreateTaskDto): TaskDto.
 * @param input CreateTaskDto — asserted against its contract at the seam.
 * @returns TaskDto — asserted before return.
 * @throws timeout — raised by task.save
 */
export async function create(input: CreateTaskDto): Promise<TaskDto> {
  const validInput = assert(CreateTaskDto, input, "task.create input");
  const taskData = new TaskData();

  // core — pure business logic, no I/O
  const out = createCore(validInput);

  // writes — side effects through the data adapters (validated before they leave)
  await taskData.save(assert(TaskDto, out.save, "task.save input"));

  return assert(TaskDto, out.result, "task.create output");
}

// Pure business logic for task.create — no I/O. Takes the
// request input; returns the dtos the writes consume plus the result.
function createCore(input: CreateTaskDto): { save: TaskDto; result: TaskDto } {
  // Recipe from [REQ] task.create: id::generate → [NEW] task → fill(title) → toDto.
  const id = Id.generate();
  const task = new Task();
  task.fill(input.title);
  task.id = id;
  const dto = task.toDto();
  return { save: dto, result: dto };
}
