// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Notification } from "./mod.ts";

Deno.test("Notification.fill", () => {
  // TODO: test fill
});

Deno.test("Notification.toDto", () => {
  // TODO: test toDto
});
