// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Batter } from "./mod.ts";

Deno.test("Batter.toDto", () => {
  // TODO: test toDto
});
