// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { CutDto } from "@/src/cake/dto/cut.ts";
import type { SlicesDto } from "@/src/cake/dto/slices.ts";
import { Slices } from "@/src/cake/domain/business/slices/mod.ts";

// Coordinator for [REQ] slices.cut(CutDto): SlicesDto.
export async function cut(input: CutDto): Promise<SlicesDto> {

  // core — pure business logic, no I/O
  const out = cutCore(input);

  return out.result;
}

// Pure business logic for slices.cut — no I/O. Takes the
// request input; returns the result.
function cutCore(input: CutDto): { result: SlicesDto } {
  const slices = new Slices();
  return { result: { sliceCount: 8 } };
}
