import { page } from "fresh";
import { define } from "../utils.ts";
import Studio from "../islands/Reference.tsx";

const SAMPLE = `[REQ] registerRecording(GetRecordingDto): IdDto
    id::create(providerName, externalId): id
    provider::pick(providerName): provider
      not-found
    [PLY] provider.getRecording(externalId): data
        [CSE] genie
        ex:provider.search(externalId): SearchDto
          not-found timeout invalid-id
        ex:provider.download(url): data
          not-found timeout
        [CSE] fiveNine
        ex:provider.fetch(externalId): data
          not-found timeout
    [NEW] metadata
    metadata.toDto(): MetadataDto
    db:metadata.set(IdDto, MetadataDto): void
      timeout network-error
    id.toDto(): IdDto


[TYP] url: string
    a URL string
[TYP] providerName: "genie" | "fiveNine"
    the name of the provider
[TYP] externalId: string
    the provider's id for the recording
[TYP] data: Uint8Array
    the binary recording data

[DTO] GetRecordingDto: providerName, externalId
    input for retrieving a recording
[DTO] SearchDto: url(s)
    a list of URLs returned by provider search
[DTO] IdDto: providerName, externalId
    unique identifier // ends in Dto
[DTO] MetadataDto: providerName
    recording metadata returned to the caller


[NON] id
    a unique identifier generated by the system
[NON] provider
    an instance of the provider class
[NON] metadata
    a key-value record of recording metadata
`;

export const handler = define.handlers({
  async GET(ctx) {
    // Read at request time so edits to data/keywords.json reflect on reload.
    // read from CWD (the studio dir in both dev and the built server) so the
    // path survives bundling — import.meta.url points into _fresh/ after build.
    const registry = JSON.parse(await Deno.readTextFile("../keywords.json"));
    const tutorial =
      new URL(ctx.req.url).searchParams.get("tutorial") === "true";
    return page({ registry, tutorial });
  },
});

export default define.page<typeof handler>(function Home({ data }) {
  return (
    <Studio
      registry={data.registry}
      example={SAMPLE}
      tutorial={data.tutorial}
    />
  );
});
