// Generated by rune manifest from corpus/valid/module-billing.rune:14.
// Edit the body. Re-running manifest will not overwrite this file.

/** the customerId */
// rune declares: [TYP] customerId: string
export type CustomerId = string;
