// Generated by rune manifest from corpus/valid/module-billing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the id
// rune declares: [TYP] id: string
export type Id = string;
