// Generated by rune manifest from corpus/valid/module-billing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsNumber, IsString } from "class-validator";

// an issued invoice
export class InvoiceDto {
  @IsString()
  id!: string;

  @IsNumber()
  amount!: number;
}
