// Generated by shape-checker manifest from corpus/valid/module-billing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// an issued invoice
export const InvoiceDtoSchema = z.object({

  id: z.unknown(), // TODO: tighten

  amount: z.unknown(), // TODO: tighten

});

export type InvoiceDto = z.infer<typeof InvoiceDtoSchema>;
