// Generated by rune manifest from corpus/valid/module-billing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsNumber, IsString } from "class-validator";

// a request to issue an invoice
export class IssueDto {
  @IsString()
  customerId!: string;

  @IsNumber()
  amount!: number;
}
