// Generated by shape-checker manifest from corpus/valid/module-billing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a request to issue an invoice
export const IssueDtoSchema = z.object({

  customerId: z.unknown(), // TODO: tighten

  amount: z.unknown(), // TODO: tighten

});

export type IssueDto = z.infer<typeof IssueDtoSchema>;
