// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Public API surface for module "notify".

export { send } from "./domain/coordinators/notification-send/mod.ts";

