// Generated by rune manifest from corpus/valid/module-billing.rune:16.
// Edit the body. Re-running manifest will not overwrite this file.

/** the amount */
// rune declares: [TYP] amount: number
export type Amount = number;
