// Generated by rune manifest from src/notify/notify.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { ReceiptDto } from "@/src/notify/dto/receipt.ts";
import { SendDto } from "@/src/notify/dto/send.ts";
import { ExService } from "@/src/core/data/ex/mod.ts";

// Data adapter for `channel` — the I/O boundary.
// Coordinators await these methods; implement each one.
// a delivery channel (email or push)
export class Channel {
  constructor(private readonly ex = new ExService()) {}
  /**
   * @param sendDto input to send a notification
   * @returns proof that a notification was delivered
   * service: ex (transport hp) — env: EX_BASE_URL
   * an external HTTP service
   * @see https://example.com/api/docs
   * @throws timeout
   * @throws invalid-address
   */
  sendEmail(sendDto: SendDto): Promise<ReceiptDto> {
    throw new Error("not implemented");
  }
  /**
   * @param sendDto input to send a notification
   * @returns proof that a notification was delivered
   * service: ex (transport hp) — env: EX_BASE_URL
   * an external HTTP service
   * @see https://example.com/api/docs
   * @throws timeout
   */
  sendPush(sendDto: SendDto): Promise<ReceiptDto> {
    throw new Error("not implemented");
  }
}
