// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Boundary methods to reach:
//   Channel.sendEmail(SendDto) (service: ex)
//   Channel.sendPush(SendDto) (service: ex)

Deno.test("channel — connectivity", () => {
  // TODO: smoke test that verifies the boundary is reachable
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});


Deno.test("invalid-address", async () => {
  // TODO: assert this fault path
});

