// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// input to create a new task
export class CreateTaskDto {
  @IsString()
  title!: string;
}
