// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the human-readable task title
// rune declares: [TYP] title: string
export type Title = string;
