// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class TaskBase {
  abstract fill(title: unknown): unknown;
  abstract save(taskDto: unknown): unknown;
  abstract toDto(): unknown;
  abstract load(id: unknown): unknown;
  abstract markDone(): unknown;
}
