// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Task } from "./mod.ts";

Deno.test("Task — placeholder", () => {
  // TODO: implement unit tests
});
