// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { CreateListDto } from "@/src/lists/dto/create-list.ts";
import type { ListDto } from "@/src/lists/dto/list.ts";

// Coordinator for [REQ] list.create(CreateListDto): ListDto.

export async function create(input: CreateListDto): Promise<ListDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
