// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { open } from "./mod.ts";

Deno.test("open — happy path", async () => {
  // TODO: implement happy path test
});

