// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { StartDto } from "@/src/checkout/dto/start.ts";
import type { TicketDto } from "@/src/checkout/dto/ticket.ts";
import { Ticket } from "@/src/checkout/domain/business/ticket/mod.ts";

// Coordinator for [REQ] ticket.open(StartDto): TicketDto.
export async function open(input: StartDto): Promise<TicketDto> {

  // core — pure business logic, no I/O
  const out = openCore(input);

  return out.result;
}

// Pure business logic for ticket.open — no I/O. Takes the
// request input; returns the result.
function openCore(input: StartDto): { result: TicketDto } {
  const _ticket = new Ticket();
  // memberId is a $external input — failing loudly here proves it actually arrived.
  if (!input.memberId) {
    throw new Error("missing memberId — external input not resolved");
  }
  return { result: { ticketId: `ticket-${input.memberId}` } };
}
