// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// the batter to bake
export class BakeDto {
  @IsString()
  batterId!: string;
}
