// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a baked-cake identifier
// rune declares: [TYP] cakeId: string
export type CakeId = string;
