// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a shopping cart identifier
// rune declares: [TYP] cartId: string
export type CartId = string;
