// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// proof the ingredients were bought
export class ReceiptDto {
  @IsString()
  ingredientsId!: string;
}
