// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a count of cake slices
// rune declares: [TYP] sliceCount: number
export type SliceCount = number;
