// Generated by rune manifest from corpus/valid/module-catalog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Recipe (from [REQ] product.list @ corpus/valid/module-catalog.rune:3):
//   1. [RET] ProductsDto

import { list } from "./mod.ts";

Deno.test("list — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

