// Generated by rune manifest from corpus/valid/module-catalog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { ListDto } from "@/src/catalog/dto/list.ts";
import { ProductsDto } from "@/src/catalog/dto/products.ts";
import { assert } from "#assert";
import { Product } from "@/src/catalog/domain/business/product/mod.ts";
import { Product as ProductData } from "@/src/catalog/domain/data/product/mod.ts";

// Coordinator for [REQ] product.list(ListDto): ProductsDto.
export async function list(input: ListDto): Promise<ProductsDto> {
  const validInput = assert(ListDto, input, "product.list input");
  const productData = new ProductData();

  // reads — load inputs through the data adapters (validated at the seam)
  const productQuery = assert(ProductsDto, await productData.query(undefined as never), "product.query");

  // core — pure business logic, no I/O
  const out = listCore(validInput, productQuery);

  return assert(ProductsDto, out.result, "product.list output");
}

// Pure business logic for product.list — no I/O. Takes the
// request input and the dtos the reads loaded; returns the result.
function listCore(input: ListDto, productQuery: ProductsDto): { result: ProductsDto } {
  const product = new Product();
  // TODO: run the pure steps on product, build the dtos
  throw new Error("not implemented");
}
