// Generated by shape-checker manifest from corpus/valid/module-catalog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Coordinator for [REQ] product.list(ListDto): ProductsDto.

export async function list(input: ListDto): Promise<ProductsDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
