// Generated by rune manifest from spec/runes/core.rune.
// Shared service client. Scaffolded once; fill in the body. `sync` preserves this file.

/**
 * db (transport SIDECAR) — env: DB_URL
 * the app's datastore boundary
 * @see https://example.com/db
 */
export class DbService {
  // This toy's real `db` boundary: an in-memory key→JSON store. Static so every
  // `new DbService()` shares one store — `create()` and `complete()` use different
  // adapter instances yet must see the same records.
  private static store = new Map<string, string>();

  // Test seam: force the NEXT put (a write/save) to reject with this fault slug, so
  // the declared `timeout` fault path can be exercised without a real service that
  // fails on demand. One-shot; cleared on use. (Reads model `not-found` naturally,
  // by returning undefined for an absent key — no seam needed.)
  static failNextPut: string | null = null;

  async put(key: string, value: unknown): Promise<void> {
    if (DbService.failNextPut) {
      const slug = DbService.failNextPut;
      DbService.failNextPut = null;
      throw new Error(slug);
    }
    DbService.store.set(key, JSON.stringify(value));
  }

  async get<T>(key: string): Promise<T | undefined> {
    const raw = DbService.store.get(key);
    return raw === undefined ? undefined : JSON.parse(raw) as T;
  }
}
