// Generated by rune manifest from spec/runes/core.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { DbService } from "./mod.ts";
import { assertEquals } from "#std/assert";

// Real boundary (the in-memory db), no mocks: a put then get round-trips a value,
// and a missing key reads back as undefined (the signal the adapter maps to not-found).
Deno.test("db — connectivity", async () => {
  const db = new DbService();
  const key = "probe:" + crypto.randomUUID();
  await db.put(key, { ok: true, n: 42 });
  assertEquals(await db.get<{ ok: boolean; n: number }>(key), { ok: true, n: 42 });
  assertEquals(await db.get("absent:" + crypto.randomUUID()), undefined);
});
