// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

Deno.test("Channel base — placeholder", () => {
  // TODO: tests against the base abstraction
});
