// Generated by rune manifest from spec/runes/notes.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Recipe (from [REQ] note.archive @ spec/runes/notes.rune:12):
//   1. note.markArchived(): note
//   2. note.toDto(): NoteDto

import { archive } from "./mod.ts";
import { create } from "@/src/notes/domain/coordinators/note-create/mod.ts";

Deno.test("archive — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("not-found", async () => {
  // TODO: assert this fault path
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

