// Generated by rune manifest from spec/runes/notes.rune:12.
// Edit the body. Re-running manifest will not overwrite this file.

import { NoteRefDto } from "@/src/notes/dto/note-ref.ts";
import { NoteDto } from "@/src/notes/dto/note.ts";
import { assert } from "#assert";
import { Note } from "@/src/notes/domain/business/note/mod.ts";
import { Note as NoteData } from "@/src/notes/domain/data/note/mod.ts";

/**
 * Coordinator for [REQ] note.archive(NoteRefDto): NoteDto.
 * @param input NoteRefDto — asserted against its contract at the seam.
 * @returns NoteDto — asserted before return.
 * @throws not-found — raised by note.load
 * @throws timeout — raised by note.save
 */
export async function archive(input: NoteRefDto): Promise<NoteDto> {
  const validInput = assert(NoteRefDto, input, "note.archive input");
  const noteData = new NoteData();

  // reads — load inputs through the data adapters (validated at the seam)
  const noteLoad = assert(NoteDto, await noteData.load(validInput.id), "note.load");

  // core — pure business logic, no I/O
  const out = archiveCore(validInput, noteLoad);

  // writes — side effects through the data adapters (validated before they leave)
  await noteData.save(assert(NoteDto, out.save, "note.save input"));

  return assert(NoteDto, out.result, "note.archive output");
}

// Pure business logic for note.archive — no I/O. Takes the
// request input and the dtos the reads loaded; returns the dtos the writes consume plus the result.
function archiveCore(input: NoteRefDto, noteLoad: NoteDto): { save: NoteDto; result: NoteDto } {
  const note = new Note();
  // Recipe from [REQ] note.archive (run in order):
  //   1. note.markArchived(): note
  //   2. note.toDto(): NoteDto
  // TODO: implement the steps above, then build the dtos
  throw new Error("not implemented");
}
