// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a unique list identifier
// rune declares: [TYP] id: string
export type Id = string;
