// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsArray, IsString } from "class-validator";

// a persisted list record
export class ListDto {
  @IsString()
  id!: string;

  @IsString()
  name!: string;

  @IsArray()
  @IsString({ each: true })
  taskIds!: string[];
}
