// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { TaskRefDto } from "@/src/tasks/dto/task-ref.ts";
import type { TaskDto } from "@/src/tasks/dto/task.ts";
import { Task } from "@/src/tasks/domain/business/task/mod.ts";
import { Task as TaskData } from "@/src/tasks/domain/data/task/mod.ts";

// Coordinator for [REQ] task.complete(TaskRefDto): TaskDto.
export async function complete(input: TaskRefDto): Promise<TaskDto> {
  const taskData = new TaskData();

  // reads — load inputs through the data adapters
  const taskLoad = await taskData.load(input.id) as TaskDto;

  // core — pure business logic, no I/O
  const out = completeCore(input, taskLoad);

  // writes — side effects through the data adapters
  await taskData.save(out.save);

  return out.result;
}

// Pure business logic for task.complete — no I/O. Takes the
// request input and the dtos the reads loaded; returns the dtos the
// writes consume plus the result.
function completeCore(input: TaskRefDto, taskLoad: TaskDto): { save: TaskDto; result: TaskDto } {
  const task = new Task();
  // TODO: run the pure steps on task, build the dtos
  throw new Error("not implemented");
}
