// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { TaskRefDto } from "@/src/tasks/dto/task-ref.ts";
import type { TaskDto } from "@/src/tasks/dto/task.ts";

// Coordinator for [REQ] task.complete(TaskRefDto): TaskDto.

export async function complete(input: TaskRefDto): Promise<TaskDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
