// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { CreateTaskDto } from "@/src/tasks/dto/create-task.ts";
import type { TaskDto } from "@/src/tasks/dto/task.ts";

// Coordinator for [REQ] task.create(CreateTaskDto): TaskDto.

export async function create(input: CreateTaskDto): Promise<TaskDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
