// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { CreateTaskDto } from "@/src/tasks/dto/create-task.ts";
import { TaskDto } from "@/src/tasks/dto/task.ts";
import { assert } from "#assert";
import { Task } from "@/src/tasks/domain/business/task/mod.ts";
import { Task as TaskData } from "@/src/tasks/domain/data/task/mod.ts";

// Coordinator for [REQ] task.create(CreateTaskDto): TaskDto.
export async function create(input: CreateTaskDto): Promise<TaskDto> {
  const validInput = assert(CreateTaskDto, input, "task.create input");
  const taskData = new TaskData();

  // core — pure business logic, no I/O
  const out = createCore(validInput);

  // writes — side effects through the data adapters (validated before they leave)
  await taskData.save(assert(TaskDto, out.save, "task.save input"));

  return assert(TaskDto, out.result, "task.create output");
}

// Pure business logic for task.create — no I/O. Takes the
// request input; returns the dtos the writes consume plus the result.
function createCore(input: CreateTaskDto): { save: TaskDto; result: TaskDto } {
  const task = new Task();
  // TODO: run the pure steps on task, build the dtos
  throw new Error("not implemented");
}
