// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { DriveDto } from "@/src/cake/dto/drive.ts";
import type { ArrivalDto } from "@/src/cake/dto/arrival.ts";
import { Arrival } from "@/src/cake/domain/business/arrival/mod.ts";

// Coordinator for [REQ] arrival.reach(DriveDto): ArrivalDto.
export async function reach(input: DriveDto): Promise<ArrivalDto> {

  // core — pure business logic, no I/O
  const out = reachCore(input);

  return out.result;
}

// Pure business logic for arrival.reach — no I/O. Takes the
// request input; returns the result.
function reachCore(input: DriveDto): { result: ArrivalDto } {
  const arrival = new Arrival();
  return { result: { storeId: "store-42" } };
}
