// Generated by rune manifest from spec/runes/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * a reference to the task to complete
 * @internal
 */
// rune declares: [DTO] CompleteTaskDto: id
export class CompleteTaskDto {
  /** a unique task identifier */
  // rune declares: [TYP] id: string
  @ApiProperty({ description: "a unique task identifier" })
  @IsString()
  id!: string;
}
