// Generated by rune manifest from spec/runes/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * input to create a new task
 * @internal
 */
// rune declares: [DTO] CreateTaskDto: title
export class CreateTaskDto {
  /** the human-readable task title */
  // rune declares: [TYP] title: string
  @ApiProperty({ description: "the human-readable task title" })
  @IsString()
  title!: string;
}
