// Generated by rune manifest from spec/runes/tasks.rune:23.
// Edit the body. Re-running manifest will not overwrite this file.

/** whether the task has been completed */
// rune declares: [TYP] done: boolean
export type Done = boolean;
