// Generated by rune manifest from spec/runes/tasks.rune:19.
// Edit the body. Re-running manifest will not overwrite this file.

/** a unique task identifier */
// rune declares: [TYP] id: string
export type Id = string;
