// Generated by rune manifest from spec/runes/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsBoolean, IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * a persisted task record
 * @internal
 */
// rune declares: [DTO] TaskDto: id, title, done
export class TaskDto {
  /** a unique task identifier */
  // rune declares: [TYP] id: string
  @ApiProperty({ description: "a unique task identifier" })
  @IsString()
  id!: string;

  /** the human-readable task title */
  // rune declares: [TYP] title: string
  @ApiProperty({ description: "the human-readable task title" })
  @IsString()
  title!: string;

  /** whether the task has been completed */
  // rune declares: [TYP] done: boolean
  @ApiProperty({ description: "whether the task has been completed" })
  @IsBoolean()
  done!: boolean;
}
