// Generated by rune manifest from spec/runes/tasks.rune:21.
// Edit the body. Re-running manifest will not overwrite this file.

/** the human-readable task title */
// rune declares: [TYP] title: string
export type Title = string;
