// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Feedback } from "./mod.ts";

Deno.test("Feedback.toDto", () => {
  // TODO: test toDto
});
