// Generated by rune manifest — DO NOT EDIT (regenerated on every `rune sync`).

// Type vocabulary (from [TYP]):
//   customerId: string — the customerId
//   amount: number — the amount
//   id: string — the id
// Public API surface for module "billing".

export { issue } from "./domain/coordinators/invoice-issue/mod.ts";

