// Generated by rune manifest from corpus/valid/module-billing.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Public API surface for module "billing".

export { issue } from "./domain/coordinators/invoice-issue/mod.ts";

