// Generated by shape-checker manifest from corpus/valid/module-catalog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Public API surface for module "catalog".

export { list } from "./domain/coordinators/product-list/mod.ts";

