// Generated by rune manifest from corpus/valid/module-catalog.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { ListDto } from "@/src/catalog/dto/list.ts";
import { ProductsDto } from "@/src/catalog/dto/products.ts";

// Data adapter for `product` — the I/O boundary.
// Coordinators await these methods; implement each one.
export class Product {
  /**
   * @param listDto a paged product listing request
   * @returns a page of products
   * @throws timeout
   */
  query(listDto: ListDto): Promise<ProductsDto> {
    throw new Error("not implemented");
  }
}
