// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { FulfillDto } from "@/src/checkout/dto/fulfill.ts";
import type { DoneDto } from "@/src/checkout/dto/done.ts";
import { Delivery } from "@/src/checkout/domain/business/delivery/mod.ts";

// Coordinator for [REQ] delivery.complete(FulfillDto): DoneDto.
export async function complete(input: FulfillDto): Promise<DoneDto> {

  // core — pure business logic, no I/O
  const out = completeCore(input);

  return out.result;
}

// Pure business logic for delivery.complete — no I/O. Takes the
// request input; returns the result.
function completeCore(input: FulfillDto): { result: DoneDto } {
  const _delivery = new Delivery();
  // paymentId arrives via the OR-bind from whichever payment branch ran.
  if (!input.paymentId) {
    throw new Error("missing paymentId — the OR-bind did not resolve");
  }
  return { result: { delivered: true } };
}
