// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Recipe (from [REQ] order.create @ corpus/valid/entrypoint.rune:6):
//   1. [RET] OrderDto

import { create } from "./mod.ts";

Deno.test("create — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

