// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { CreateListDto } from "@/src/lists/dto/create-list.ts";
import { ListDto } from "@/src/lists/dto/list.ts";
import { assert } from "#assert";
import { List } from "@/src/lists/domain/business/list/mod.ts";
import { List as ListData } from "@/src/lists/domain/data/list/mod.ts";

// Coordinator for [REQ] list.create(CreateListDto): ListDto.
export async function create(input: CreateListDto): Promise<ListDto> {
  const validInput = assert(CreateListDto, input, "list.create input");
  const listData = new ListData();

  // core — pure business logic, no I/O
  const out = createCore(validInput);

  // writes — side effects through the data adapters (validated before they leave)
  await listData.save(assert(ListDto, out.save, "list.save input"));

  return assert(ListDto, out.result, "list.create output");
}

// Pure business logic for list.create — no I/O. Takes the
// request input; returns the dtos the writes consume plus the result.
function createCore(input: CreateListDto): { save: ListDto; result: ListDto } {
  const list = new List();
  // TODO: run the pure steps on list, build the dtos
  throw new Error("not implemented");
}
