// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { List } from "./mod.ts";

Deno.test("List — placeholder", () => {
  // TODO: implement unit tests
});
