// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// input to add a task to a list
export class AddTaskDto {
  @IsString()
  id!: string;

  @IsString()
  taskId!: string;
}
