// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// input to add a task to a list
export const AddTaskDtoSchema = z.object({

  id: z.unknown(), // TODO: tighten

  taskId: z.unknown(), // TODO: tighten

});

export type AddTaskDto = z.infer<typeof AddTaskDtoSchema>;
