// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// input to create a new list
export class CreateListDto {
  @IsString()
  name!: string;
}
