// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the list name
// rune declares: [TYP] name: string
export const nameSchema = z.unknown(); // TODO: tighten to string
export type name = z.infer<typeof nameSchema>;
