// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// an id of a task placed on the list
// rune declares: [TYP] taskId: string
export const taskIdSchema = z.unknown(); // TODO: tighten to string
export type taskId = z.infer<typeof taskIdSchema>;
