// Generated by rune manifest from spec/runes/tasks.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { TaskDto } from "@/src/tasks/dto/task.ts";
import { DbService } from "@/src/core/data/db/mod.ts";

// Data adapter for `task` — the I/O boundary.
// Coordinators await these methods; implement each one.
// a single todo item
export class Task {
  constructor(private readonly db = new DbService()) {}
  /**
   * @param title the human-readable task title
   */
  fill(title: string): Promise<Task> {
    throw new Error("not implemented");
  }
  /**
   * @param taskDto a persisted task record
   * service: db (transport SIDECAR) — env: DB_URL
   * the app's datastore boundary
   * @see https://example.com/db
   * @throws timeout
   */
  save(taskDto: TaskDto): Promise<void> {
    return this.db.put(`task:${taskDto.id}`, taskDto);
  }
  /**
   * @returns a persisted task record
   */
  toDto(): Promise<TaskDto> {
    throw new Error("not implemented");
  }
  /**
   * @param id a unique task identifier
   * @returns a persisted task record
   * service: db (transport SIDECAR) — env: DB_URL
   * the app's datastore boundary
   * @see https://example.com/db
   * @throws not-found
   */
  async load(id: string): Promise<TaskDto> {
    const found = await this.db.get<TaskDto>(`task:${id}`);
    if (found === undefined) throw new Error("not-found");
    return found;
  }
  markDone(): Promise<Task> {
    throw new Error("not implemented");
  }
}
