// Generated by rune manifest from spec/runes/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Task as TaskData } from "./mod.ts";
import { DbService } from "@/src/core/data/db/mod.ts";
import { TaskDto } from "@/src/tasks/dto/task.ts";
import { assertEquals, assertRejects } from "#std/assert";

function taskDto(id: string, title: string, done: boolean): TaskDto {
  return Object.assign(new TaskDto(), { id, title, done });
}

// Real boundary (the in-memory db), no mocks: a save then load round-trips a record.
Deno.test("task — connectivity", async () => {
  const adapter = new TaskData();
  const dto = taskDto(crypto.randomUUID(), "smoke", false);
  await adapter.save(dto);
  const loaded = await adapter.load(dto.id);
  assertEquals(loaded.id, dto.id);
  assertEquals(loaded.title, "smoke");
  assertEquals(loaded.done, false);
});

// load() maps an absent record to the declared `not-found` fault.
Deno.test("not-found", async () => {
  const adapter = new TaskData();
  await assertRejects(
    () => adapter.load("missing-" + crypto.randomUUID()),
    Error,
    "not-found",
  );
});

// save() propagates a db write failure as the declared `timeout` fault.
Deno.test("timeout", async () => {
  const adapter = new TaskData();
  DbService.failNextPut = "timeout";
  await assertRejects(
    () => adapter.save(taskDto(crypto.randomUUID(), "x", false)),
    Error,
    "timeout",
  );
});
