// Generated by rune manifest from spec/runes/notes.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Recipe (from [REQ] note.create @ spec/runes/notes.rune:3):
//   1. id::generate(): id
//   2. [NEW] note
//   3. note.fill(body): note
//   4. note.toDto(): NoteDto

import { create } from "./mod.ts";

Deno.test("create — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

