// Generated by rune manifest from spec/runes/notes.rune:3.
// Edit the body. Re-running manifest will not overwrite this file.

import { CreateNoteDto } from "@/src/notes/dto/create-note.ts";
import { NoteDto } from "@/src/notes/dto/note.ts";
import { assert } from "#assert";
import { Id } from "@/src/notes/domain/business/id/mod.ts";
import { Note } from "@/src/notes/domain/business/note/mod.ts";
import { Note as NoteData } from "@/src/notes/domain/data/note/mod.ts";

/**
 * Coordinator for [REQ] note.create(CreateNoteDto): NoteDto.
 * @param input CreateNoteDto — asserted against its contract at the seam.
 * @returns NoteDto — asserted before return.
 * @throws timeout — raised by note.save
 */
export async function create(input: CreateNoteDto): Promise<NoteDto> {
  const validInput = assert(CreateNoteDto, input, "note.create input");
  const noteData = new NoteData();

  // core — pure business logic, no I/O
  const out = createCore(validInput);

  // writes — side effects through the data adapters (validated before they leave)
  await noteData.save(assert(NoteDto, out.save, "note.save input"));

  return assert(NoteDto, out.result, "note.create output");
}

// Pure business logic for note.create — no I/O. Takes the
// request input; returns the dtos the writes consume plus the result.
function createCore(input: CreateNoteDto): { save: NoteDto; result: NoteDto } {
  const note = new Note();
  // Recipe from [REQ] note.create (run in order):
  //   1. id::generate(): id
  //   2. [NEW] note
  //   3. note.fill(body): note
  //   4. note.toDto(): NoteDto
  // TODO: implement the steps above, then build the dtos
  throw new Error("not implemented");
}
