// Generated by rune manifest from corpus/valid/entrypoint.rune:11.
// Edit the body. Re-running manifest will not overwrite this file.

import { PayDto } from "@/src/checkout/dto/pay.ts";
import { ReceiptDto } from "@/src/checkout/dto/receipt.ts";
import { assert } from "#assert";
import { Payment as PaymentData } from "@/src/checkout/domain/data/payment/mod.ts";

/**
 * Coordinator for [REQ] payment.pay(PayDto): ReceiptDto.
 * @param input PayDto — asserted against its contract at the seam.
 * @returns ReceiptDto — asserted before return.
 * @throws timeout — raised by payment.charge
 */
export async function pay(input: PayDto): Promise<ReceiptDto> {
  const validInput = assert(PayDto, input, "payment.pay input");
  const paymentData = new PaymentData();

  // core — pure business logic, no I/O
  payCore(validInput);

  // after the core — boundary calls in spec order (validated at the seam)
  // (guards run in the core above: a throw there prevents every call below)
  const paymentCharge = assert(ReceiptDto, await paymentData.charge(validInput), "payment.charge");

  return paymentCharge;
}

// Pure business logic for payment.pay — no I/O. Takes the
// request input; returns nothing (the post-core boundary calls produce the flow's values).
function payCore(input: PayDto): void {
  // Recipe from [REQ] payment.pay (run in order):
  //   1. [RET] ReceiptDto
  // TODO: implement the steps above, then build the dtos
  throw new Error("not implemented");
}
