// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { bake } from "./mod.ts";

Deno.test("bake — happy path", async () => {
  // TODO: implement happy path test
});

