// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { BakeDto } from "@/src/cake/dto/bake.ts";
import type { CakeDto } from "@/src/cake/dto/cake.ts";
import { Confection } from "@/src/cake/domain/business/confection/mod.ts";

// Coordinator for [REQ] confection.bake(BakeDto): CakeDto.
export async function bake(input: BakeDto): Promise<CakeDto> {

  // core — pure business logic, no I/O
  const out = bakeCore(input);

  return out.result;
}

// Pure business logic for confection.bake — no I/O. Takes the
// request input; returns the result.
function bakeCore(input: BakeDto): { result: CakeDto } {
  const confection = new Confection();
  return { result: { cakeId: `cake-${input.batterId}` } };
}
