// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { addTask } from "./mod.ts";

Deno.test("addTask — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("not-found", async () => {
  // TODO: assert this fault path
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

