// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { AddTaskDto } from "@/src/lists/dto/add-task.ts";
import type { ListDto } from "@/src/lists/dto/list.ts";

// Coordinator for [REQ] list.addTask(AddTaskDto): ListDto.

export async function addTask(input: AddTaskDto): Promise<ListDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
