// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { AddTaskDto } from "@/src/lists/dto/add-task.ts";
import type { ListDto } from "@/src/lists/dto/list.ts";
import { List } from "@/src/lists/domain/business/list/mod.ts";
import { List as ListData } from "@/src/lists/domain/data/list/mod.ts";

// Coordinator for [REQ] list.addTask(AddTaskDto): ListDto.
export async function addTask(input: AddTaskDto): Promise<ListDto> {
  const listData = new ListData();

  // reads — load inputs through the data adapters
  const listLoad = await listData.load(input.id) as ListDto;

  // core — pure business logic, no I/O
  const out = addTaskCore(input, listLoad);

  // writes — side effects through the data adapters
  await listData.save(out.save);

  return out.result;
}

// Pure business logic for list.addTask — no I/O. Takes the
// request input and the dtos the reads loaded; returns the dtos the
// writes consume plus the result.
function addTaskCore(input: AddTaskDto, listLoad: ListDto): { save: ListDto; result: ListDto } {
  const list = new List();
  // TODO: run the pure steps on list, build the dtos
  throw new Error("not implemented");
}
