// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { AddTaskDto } from "@/src/lists/dto/add-task.ts";
import { ListDto } from "@/src/lists/dto/list.ts";
import { assert } from "#assert";
import { List } from "@/src/lists/domain/business/list/mod.ts";
import { List as ListData } from "@/src/lists/domain/data/list/mod.ts";

// Coordinator for [REQ] list.addTask(AddTaskDto): ListDto.
export async function addTask(input: AddTaskDto): Promise<ListDto> {
  const validInput = assert(AddTaskDto, input, "list.addTask input");
  const listData = new ListData();

  // reads — load inputs through the data adapters (validated at the seam)
  const listLoad = assert(ListDto, await listData.load(validInput.id), "list.load");

  // core — pure business logic, no I/O
  const out = addTaskCore(validInput, listLoad);

  // writes — side effects through the data adapters (validated before they leave)
  await listData.save(assert(ListDto, out.save, "list.save input"));

  return assert(ListDto, out.result, "list.addTask output");
}

// Pure business logic for list.addTask — no I/O. Takes the
// request input and the dtos the reads loaded; returns the dtos the writes consume plus the result.
function addTaskCore(input: AddTaskDto, listLoad: ListDto): { save: ListDto; result: ListDto } {
  const list = new List();
  // TODO: run the pure steps on list, build the dtos
  throw new Error("not implemented");
}
