// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a unique notification id
// rune declares: [TYP] id: string
export type Id = string;
