// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the delivery status of the notification
// rune declares: [TYP] status: string
export type Status = string;
