// Generated by rune manifest from corpus/valid/module-billing.rune:3.
// Edit the body. Re-running manifest will not overwrite this file.

import { IssueDto } from "@/src/billing/dto/issue.ts";
import { InvoiceDto } from "@/src/billing/dto/invoice.ts";
import { assert } from "#assert";
import { Invoice as InvoiceData } from "@/src/billing/domain/data/invoice/mod.ts";

/**
 * Coordinator for [REQ] invoice.issue(IssueDto): InvoiceDto.
 * @param input IssueDto — asserted against its contract at the seam.
 * @returns InvoiceDto — asserted before return.
 * @throws timeout — raised by invoice.save
 */
export async function issue(input: IssueDto): Promise<InvoiceDto> {
  const validInput = assert(IssueDto, input, "invoice.issue input");
  const invoiceData = new InvoiceData();

  // reads — load inputs through the data adapters (validated at the seam)
  const invoiceSave = assert(InvoiceDto, await invoiceData.save(validInput), "invoice.save");

  // core — pure business logic, no I/O
  const out = issueCore(validInput, invoiceSave);

  return assert(InvoiceDto, out.result, "invoice.issue output");
}

// Pure business logic for invoice.issue — no I/O. Takes the
// request input and the dtos the reads loaded; returns the result.
function issueCore(input: IssueDto, invoiceSave: InvoiceDto): { result: InvoiceDto } {
  // Recipe from [REQ] invoice.issue (run in order):
  //   1. [RET] InvoiceDto
  // TODO: implement the steps above, then build the dtos
  throw new Error("not implemented");
}
