// Generated by shape-checker manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Public API surface for module "checkout".

export { place } from "./domain/coordinators/order-place/mod.ts";

