// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// an id of a task placed on the list
// rune declares: [TYP] taskId: string
export type TaskId = string;
