// Sig/impl split for business features and data adapters. The spec owns the
// signature surface; the impl carries the bodies. With `noImplicitOverride`
// enabled in the synced project, `deno check` then catches method-level drift
// in both directions:
//   - method added to the spec  → abstract member not implemented (TS2515)
//   - method removed from spec   → orphaned `override` on the impl  (TS4113)
//
// Signatures use `unknown` for params/returns: this rule cares about method
// PRESENCE (add/remove). Exact input/output DTO parity for coordinators and
// entrypoints is enforced separately by rune-signature-parity.

import {
  type CseNode,
  type RuneAst,
  type StepLike,
} from "@rune/domain/business/rune-parse/mod.ts";

export interface MethodSig {
  verb: string;
  params: string[];
  isStatic: boolean;
}

// Group method signatures by noun across every [REQ] flow. Polymorphic ([PLY])
// nouns are excluded — they get base/implementations, not a sig/impl split.
export function collectNounMethods(ast: RuneAst): Map<string, MethodSig[]> {
  const byNoun = new Map<string, MethodSig[]>();
  const polyNouns = new Set<string>();

  const add = (noun: string, sig: MethodSig): void => {
    const list = byNoun.get(noun) ?? [];
    if (!list.some((m) => m.verb === sig.verb && m.isStatic === sig.isStatic)) {
      list.push(sig);
    }
    byNoun.set(noun, list);
  };

  const walk = (steps: StepLike[] | CseNode["steps"]): void => {
    for (const step of steps) {
      if (step.kind === "step" || step.kind === "boundary") {
        add(step.noun, {
          verb: step.verb,
          params: step.params,
          isStatic: step.isStatic,
        });
      } else if (step.kind === "ply") {
        polyNouns.add(step.noun);
        for (const cse of step.cases) walk(cse.steps);
      }
    }
  };

  for (const req of ast.reqs) walk(req.steps);
  for (const noun of polyNouns) byNoun.delete(noun);
  return byNoun;
}

// Spec-owned sig.ts: abstract base (instance methods) + statics interface.
export function renderSig(noun: string, methods: MethodSig[]): string {
  const pascal = toPascal(noun);
  const instance = methods.filter((m) => !m.isStatic);
  const statics = methods.filter((m) => m.isStatic);

  const lines: string[] = [];
  lines.push(
    "// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.",
  );
  lines.push("");
  lines.push(`export abstract class ${pascal}Base {`);
  for (const m of instance) {
    lines.push(`  abstract ${m.verb}(${renderParams(m.params)}): unknown;`);
  }
  lines.push("}");
  if (statics.length > 0) {
    lines.push("");
    lines.push(`export interface ${pascal}Statics {`);
    for (const m of statics) {
      lines.push(`  ${m.verb}(${renderParams(m.params)}): unknown;`);
    }
    lines.push("}");
  }
  lines.push("");
  return lines.join("\n");
}

// Scaffolded-once impl: extends the base, marks instance methods `override`,
// declares statics, and asserts the static surface via `satisfies`.
export function renderImpl(noun: string, methods: MethodSig[]): string {
  const pascal = toPascal(noun);
  const instance = methods.filter((m) => !m.isStatic);
  const statics = methods.filter((m) => m.isStatic);

  const lines: string[] = [];
  lines.push(
    "// Scaffolded once; fill in the bodies. `sync` preserves this file.",
  );
  if (statics.length > 0) {
    lines.push(
      `import { ${pascal}Base, type ${pascal}Statics } from "./sig.ts";`,
    );
  } else {
    lines.push(`import { ${pascal}Base } from "./sig.ts";`);
  }
  lines.push("");
  lines.push(`export class ${pascal} extends ${pascal}Base {`);
  for (const m of statics) {
    lines.push(`  static ${m.verb}(${renderParams(m.params)}): unknown {`);
    lines.push(`    throw new Error("not implemented");`);
    lines.push("  }");
  }
  for (const m of instance) {
    lines.push(`  override ${m.verb}(${renderParams(m.params)}): unknown {`);
    lines.push(`    throw new Error("not implemented");`);
    lines.push("  }");
  }
  lines.push("}");
  if (statics.length > 0) {
    lines.push("");
    lines.push(`${pascal} satisfies ${pascal}Statics;`);
  }
  lines.push("");
  return lines.join("\n");
}

// ---- helpers ----

/** Render a rune param list as typed TS params (`name: unknown`), deduping and
 * sanitising identifiers. Shared with the poly templates so base/impl method
 * signatures type-check the same way the sig/impl split does. */
export function renderParams(params: string[]): string {
  const seen = new Set<string>();
  return params
    .map((p, i) => {
      let id = toCamelIdent(p);
      if (id === "" || seen.has(id)) id = `arg${i}`;
      seen.add(id);
      return `${id}: unknown`;
    })
    .join(", ");
}

export function toPascal(name: string): string {
  return name
    .split(/[-_]/)
    .filter((s) => s.length > 0)
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join("");
}

function toCamelIdent(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, "");
  if (cleaned === "") return "";
  return cleaned[0].toLowerCase() + cleaned.slice(1);
}
