// Concrete-class generation for business features and data adapters. A noun's
// methods (collected across every [REQ] flow) become a plain class with stubbed
// bodies — no abstract base, no sig.ts. Polymorphic ([PLY]) nouns are excluded;
// they get an abstract base + variant implementations via the poly-* templates.
//
// Signatures resolve through the spec's [DTO]/[TYP] declarations when the
// caller threads them in (RenderImplOptions); anything unresolvable stays
// `unknown` — tighten as you implement. Exact input/output DTO parity for
// coordinators/entrypoints is enforced separately by rune-signature-parity.

import {
  type CseNode,
  type DtoNode,
  type NonNode,
  type RuneAst,
  type SrvNode,
  type StepLike,
  type TypNode,
} from "@rune/domain/business/rune-parse/mod.ts";
import {
  applyCase,
  type Binding,
  transformName,
} from "@rune/domain/business/rune-bindings/mod.ts";

export interface MethodSig {
  verb: string;
  params: string[];
  /** The step's declared return ("TaskDto", "id", "void", "" when omitted). */
  output: string;
  isStatic: boolean;
  /** Fault slugs declared on this step, UNIONed across every flow that calls
   * the method — emitted as `@throws` doc on the generated method (E13). */
  faults: string[];
  /** For a boundary method, the declared [SRV] service it calls — drives the
   * service/transport/env doc on the adapter method (E20). */
  service?: string;
}

/** Type resolution + signature shape for renderImpl. All optional: with no
 * options the output is the legacy `unknown`-typed sync stub. */
export interface RenderImplOptions {
  /** Wrap returns in Promise<…> — data adapters are awaited by coordinators. */
  async?: boolean;
  /** [TYP] declarations by name: params/returns resolve to their primitive. */
  typMap?: Map<string, TypNode>;
  /** [DTO] declarations by name: Dto-suffixed names resolve to the class. */
  dtoByName?: Map<string, DtoNode>;
  /** Module + <name> binding for the isCore-aware DTO import paths. */
  module?: string;
  nameBinding?: Binding;
  /** Spec path — emits the `// Generated by rune manifest from <path>.`
   * provenance header above the scaffold note (E12). */
  runePath?: string;
  /** [NON] declarations by noun: the prose becomes the class doc comment, and
   * for adapters (async) it rides under the I/O-boundary role line (E12/E18). */
  nonByNoun?: Map<string, NonNode>;
  /** [SRV] declarations by name: an adapter method calling `service:noun.verb`
   * documents its backing service, transport, and env vars (E20). */
  srvByName?: Map<string, SrvNode>;
  /** Names of SHARED services (from core.rune). An adapter imports the shared
   * `src/core/data/<name>` client + constructs it ONLY for these; a legacy
   * local `[SRV]` keeps the JSDoc-only doc (no client to import). */
  sharedSrvNames?: Set<string>;
}

// Group method signatures by noun across every [REQ] flow, INCLUDING the
// boundary methods of a noun that is also a [PLY] dispatch noun — those still
// need a data adapter (a noun can be polymorphic for one verb AND a plain
// boundary for another, e.g. gateway.authorize [PLY] + gateway.capture). The
// poly noun's BUSINESS class is suppressed by the caller (walkStepsForFiles),
// not here — deleting the whole noun starved its adapter (a TS2339 bug).
export function collectNounMethods(ast: RuneAst): Map<string, MethodSig[]> {
  const byNoun = new Map<string, MethodSig[]>();

  const add = (noun: string, sig: MethodSig): void => {
    const list = byNoun.get(noun) ?? [];
    // Same verb+arity across flows is ONE method — union its faults rather than
    // first-write-wins, which would silently drop a fault declared on a later
    // call of the same method (E13).
    const existing = list.find((m) =>
      m.verb === sig.verb && m.isStatic === sig.isStatic
    );
    if (existing) {
      for (const f of sig.faults) {
        if (!existing.faults.includes(f)) existing.faults.push(f);
      }
      if (!existing.service && sig.service) existing.service = sig.service;
    } else {
      list.push({ ...sig, faults: [...sig.faults] });
    }
    byNoun.set(noun, list);
  };

  const walk = (steps: StepLike[] | CseNode["steps"]): void => {
    for (const step of steps) {
      if (step.kind === "step" || step.kind === "boundary") {
        add(step.noun, {
          verb: step.verb,
          params: step.params,
          output: step.output,
          isStatic: step.isStatic,
          faults: step.faults ?? [],
          service: step.kind === "boundary" ? step.service : undefined,
        });
      } else if (step.kind === "ply") {
        // The [PLY] verb itself is the abstract base/variants (not a concrete
        // method here); but its CASE steps (often boundary calls on the same
        // noun) still need adapter methods, so walk them.
        for (const cse of step.cases) walk(cse.steps);
      }
    }
  };

  for (const req of ast.reqs) walk(req.steps);
  return byNoun;
}

// Scaffolded-once impl: a plain concrete class. Statics and instance methods
// from the spec, bodies stubbed. No abstract base, no `override`, no sig import.
// With opts the signatures are typed from the spec's [DTO]/[TYP] declarations;
// adapter classes (opts.async) get Promise-wrapped returns (the coordinator
// awaits them). Bodies throw, so the un-`async` Promise signatures type-check
// without tripping deno lint's require-await.
export function renderImpl(
  noun: string,
  methods: MethodSig[],
  opts: RenderImplOptions = {},
): string {
  const pascal = toPascal(noun);
  const instance = methods.filter((m) => !m.isStatic);
  const statics = methods.filter((m) => m.isStatic);
  const usedDtos = new Set<string>();
  // Distinct backing services this adapter calls (boundary methods whose [SRV]
  // resolves). Each becomes a shared-client import from src/core/data/<name>
  // PLUS a default-constructed constructor field — the field keeps the import
  // used (deno lint) and hands the dev the client to implement against.
  const serviceNames = opts.async
    ? [...new Set(
      methods
        .map((m) => m.service)
        .filter((s): s is string => !!s && !!opts.sharedSrvNames?.has(s)),
    )].sort()
    : [];
  const camelName = (n: string): string => {
    const p = toPascal(n);
    return p.length ? p[0].toLowerCase() + p.slice(1) : p;
  };

  const resolve = (name: string): string =>
    resolveType(name, opts, usedDtos) ?? "unknown";
  const ret = (m: MethodSig): string => {
    const t = resolveOutput(noun, m.output, opts, usedDtos);
    return opts.async ? `Promise<${t}>` : t;
  };
  // The description of a [TYP]/[DTO] name (for @param/@returns), or "".
  const descFor = (name: string): string =>
    (/Dto$/.test(name)
      ? opts.dtoByName?.get(name)?.description
      : opts.typMap?.get(name)?.description) ?? "";

  // One method, with a JSDoc block carrying @param (typed-field prose), @returns,
  // and @throws (declared faults). Empty block is omitted entirely.
  const emitMethod = (m: MethodSig, isStaticKw: boolean): void => {
    const doc: string[] = [];
    for (const { ident, source } of paramIdentList(m.params)) {
      const d = descFor(source);
      if (d) doc.push(`@param ${ident} ${d}`);
    }
    const rd = descFor(m.output);
    if (rd && m.output !== "void" && m.output !== noun) doc.push(`@returns ${rd}`);
    // Backing-service metadata for an adapter method (E20): which [SRV] it calls,
    // its transport, and the env vars to wire — the context the dev was missing.
    if (opts.async && m.service) {
      const srv = opts.srvByName?.get(m.service);
      if (srv) {
        const env = srv.envVars.length ? ` — env: ${srv.envVars.join(", ")}` : "";
        doc.push(`service: ${srv.name} (transport ${srv.transport})${env}`);
        if (srv.description) doc.push(srv.description);
        if (srv.docsLink) doc.push(`@see ${srv.docsLink}`);
      } else {
        doc.push(`service: ${m.service} (no [SRV] declared)`);
      }
    }
    for (const f of m.faults ?? []) doc.push(`@throws ${f}`);
    if (doc.length) {
      body.push("  /**");
      for (const d of doc) body.push(`   * ${d}`);
      body.push("   */");
    }
    const kw = isStaticKw ? "static " : "";
    body.push(`  ${kw}${m.verb}(${renderParams(m.params, resolve)}): ${ret(m)} {`);
    body.push(`    throw new Error("not implemented");`);
    body.push("  }");
  };

  const body: string[] = [];
  // Class-level doc: an adapter announces its I/O-boundary role; both kinds carry
  // the [NON] prose so the domain object's meaning rides on the class (E12/E18).
  if (opts.async) {
    body.push("// Data adapter for `" + noun + "` — the I/O boundary.");
    body.push("// Coordinators await these methods; implement each one.");
  }
  const nonDesc = opts.nonByNoun?.get(noun)?.description;
  if (nonDesc) body.push(`// ${nonDesc}`);
  body.push(`export class ${pascal} {`);
  if (serviceNames.length > 0) {
    const params = serviceNames
      .map((n) => `private readonly ${camelName(n)} = new ${toPascal(n)}Service()`)
      .join(", ");
    body.push(`  constructor(${params}) {}`);
  }
  for (const m of statics) emitMethod(m, true);
  for (const m of instance) emitMethod(m, false);
  body.push("}");

  const lines: string[] = [];
  if (opts.runePath) {
    lines.push(`// Generated by rune manifest from ${opts.runePath}.`);
  }
  lines.push(
    "// Scaffolded once; fill in the bodies. `sync` preserves this file.",
  );
  lines.push("");
  for (const name of [...usedDtos].sort()) {
    const node = opts.dtoByName?.get(name);
    const dir = node?.isCore ? "src/core/dto" : `src/${opts.module}/dto`;
    const file = transformName(name, opts.nameBinding!);
    lines.push(`import { ${name} } from "@/${dir}/${file}.ts";`);
  }
  for (const name of serviceNames) {
    lines.push(
      `import { ${toPascal(name)}Service } from "@/src/core/data/${
        applyCase(name, "kebab")
      }/mod.ts";`,
    );
  }
  if (usedDtos.size > 0 || serviceNames.length > 0) lines.push("");
  lines.push(...body);
  lines.push("");
  return lines.join("\n");
}

// ---- type resolution ----

// A name resolves to a [DTO] class (recorded for import) or a [TYP] primitive;
// null = no contract in the spec.
function resolveType(
  name: string,
  opts: RenderImplOptions,
  usedDtos: Set<string>,
): string | null {
  if (
    /Dto$/.test(name) && opts.dtoByName?.has(name) && opts.module &&
    opts.nameBinding
  ) {
    usedDtos.add(name);
    return name;
  }
  switch (opts.typMap?.get(name)?.typeName) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "Uint8Array":
      return "Uint8Array";
  }
  return null;
}

// Return types additionally understand `void`, the noun itself (a fluent step
// like `task.normalize(): task` returns the class), and "" → unknown.
function resolveOutput(
  noun: string,
  output: string,
  opts: RenderImplOptions,
  usedDtos: Set<string>,
): string {
  const resolved = resolveType(output, opts, usedDtos);
  if (resolved !== null) return resolved;
  if (output === "void") return "void";
  if (output === noun) return toPascal(noun);
  return "unknown";
}

// ---- helpers ----

/** Render a rune param list as typed TS params, deduping and sanitising
 * identifiers. Types come from `resolve` (default: `unknown` — the poly
 * templates keep that shape so base/impl method signatures type-check). */
export function renderParams(
  params: string[],
  resolve: (name: string) => string = () => "unknown",
): string {
  return paramIdentList(params)
    .map(({ ident, source }) => `${ident}: ${resolve(source)}`)
    .join(", ");
}

/** The emitted TS identifier for each rune param, paired with its source name
 * (the [TYP]/[DTO] to look up for @param prose). Mirrors renderParams' renaming
 * exactly — empty/duplicate identifiers collapse to argN — so the JSDoc names
 * always match the rendered signature (E14). */
function paramIdentList(
  params: string[],
): { ident: string; source: string }[] {
  const seen = new Set<string>();
  return params.map((p, i) => {
    let id = toCamelIdent(p);
    if (id === "" || seen.has(id)) id = `arg${i}`;
    seen.add(id);
    return { ident: id, source: p };
  });
}

export function toPascal(name: string): string {
  return name
    .split(/[-_]/)
    .filter((s) => s.length > 0)
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join("");
}

function toCamelIdent(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, "");
  if (cleaned === "") return "";
  return cleaned[0].toLowerCase() + cleaned.slice(1);
}
