// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Polymorphic barrel for "Channel". Re-exports the active variant.
export { default } from "./implementations/email/mod.ts";
