// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { PayDto } from "@/src/checkout/dto/pay.ts";
import { ReceiptDto } from "@/src/checkout/dto/receipt.ts";

// Data adapter for `payment` — the I/O boundary.
// Coordinators await these methods; implement each one.
export class Payment {
  /**
   * @param payDto a payment for an order
   * @returns a receipt for a payment
   * service: db (no [SRV] declared)
   * @throws timeout
   */
  charge(payDto: PayDto): Promise<ReceiptDto> {
    throw new Error("not implemented");
  }
}
