// Generated by rune manifest from corpus/valid/module-catalog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the items
// rune declares: [TYP] items: string
export type Items = string;
