// Generated by rune manifest from corpus/valid/module-catalog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsNumber } from "class-validator";

// a paged product listing request
export class ListDto {
  @IsNumber()
  page!: number;
}
