// Generated by shape-checker manifest from corpus/valid/module-catalog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a paged product listing request
export const ListDtoSchema = z.object({

  page: z.unknown(), // TODO: tighten

});

export type ListDto = z.infer<typeof ListDtoSchema>;
