// Generated by rune manifest from corpus/valid/module-catalog.rune:14.
// Edit the body. Re-running manifest will not overwrite this file.

/** the page */
// rune declares: [TYP] page: number
export type Page = number;
