// Generated by shape-checker manifest from corpus/valid/module-catalog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a page of products
export const ProductsDtoSchema = z.object({

  items: z.unknown(), // TODO: tighten

});

export type ProductsDto = z.infer<typeof ProductsDtoSchema>;
