// Generated by rune manifest from corpus/valid/module-catalog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// a page of products
export class ProductsDto {
  @IsString()
  items!: string;
}
