// Generated by rune manifest from spec/runes/notes.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { NoteDto } from "@/src/notes/dto/note.ts";

// a single note
export class Note {
  /**
   * @param body the note body text
   */
  fill(body: string): Note {
    throw new Error("not implemented");
  }
  /**
   * @param noteDto a persisted note record
   * @throws timeout
   */
  save(noteDto: NoteDto): void {
    throw new Error("not implemented");
  }
  /**
   * @returns a persisted note record
   */
  toDto(): NoteDto {
    throw new Error("not implemented");
  }
  /**
   * @param id a unique note identifier
   * @returns a persisted note record
   * @throws not-found
   */
  load(id: string): NoteDto {
    throw new Error("not implemented");
  }
  markArchived(): Note {
    throw new Error("not implemented");
  }
}
