// Generated by rune manifest from spec/runes/notes.rune.
// Edit the body. Re-running manifest will not overwrite this file.
// Note: a single note

import { Note } from "./mod.ts";

Deno.test("Note.fill", () => {
  // Arrange — const subject = new Note();
  // Act — fill(body): note
  // Assert — TODO: assert the note result
});

Deno.test("Note.save", () => {
  // Arrange — const subject = new Note();
  // Act — save(NoteDto): void
  // Assert — TODO: assert the side effect
});

Deno.test("Note.toDto", () => {
  // Arrange — const subject = new Note();
  // Act — toDto(): NoteDto
  // Assert — TODO: assert the NoteDto result
});

Deno.test("Note.load", () => {
  // Arrange — const subject = new Note();
  // Act — load(id): NoteDto
  // Assert — TODO: assert the NoteDto result
});

Deno.test("Note.markArchived", () => {
  // Arrange — const subject = new Note();
  // Act — markArchived(): note
  // Assert — TODO: assert the note result
});
