// Generated by rune manifest from src/tasks/tasks.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { TaskDto } from "@/src/tasks/dto/task.ts";
import { DbService } from "@/src/core/data/db/mod.ts";

// Data adapter for `task` — the I/O boundary.
// Coordinators await these methods; implement each one.
// a single todo item
export class Task {
  constructor(private readonly db = new DbService()) {}
  /**
   * @param title the human-readable task title
   */
  fill(title: string): Promise<Task> {
    throw new Error("not implemented");
  }
  /**
   * @param taskDto a persisted task record
   * service: db (transport sc) — env: DB_URL
   * the project's primary datastore (sidecar)
   * @see https://docs.example.com/datastore
   * @throws timeout
   */
  save(taskDto: TaskDto): Promise<void> {
    throw new Error("not implemented");
  }
  /**
   * @returns a persisted task record
   */
  toDto(): Promise<TaskDto> {
    throw new Error("not implemented");
  }
  /**
   * @param id a unique task identifier
   * @returns a persisted task record
   * service: db (transport sc) — env: DB_URL
   * the project's primary datastore (sidecar)
   * @see https://docs.example.com/datastore
   * @throws not-found
   */
  load(id: string): Promise<TaskDto> {
    throw new Error("not implemented");
  }
  markDone(): Promise<Task> {
    throw new Error("not implemented");
  }
}
