// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Boundary methods to reach:
//   Task.fill(title)
//   Task.save(TaskDto) (service: db)
//   Task.toDto()
//   Task.load(id) (service: db)
//   Task.markDone()

Deno.test("task — connectivity", () => {
  // TODO: smoke test that verifies the boundary is reachable
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});


Deno.test("not-found", async () => {
  // TODO: assert this fault path
});

