// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Boundary methods to reach:
//   List.fill(name)
//   List.save(ListDto) (service: db)
//   List.toDto()
//   List.load(id) (service: db)
//   List.append(taskId)

Deno.test("list — connectivity", () => {
  // TODO: smoke test that verifies the boundary is reachable
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});


Deno.test("not-found", async () => {
  // TODO: assert this fault path
});

