// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { send } from "./mod.ts";

Deno.test("send — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});


Deno.test("invalid-address", async () => {
  // TODO: assert this fault path
});

