// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { SendDto } from "@/src/notify/dto/send.ts";
import type { ReceiptDto } from "@/src/notify/dto/receipt.ts";

// Coordinator for [REQ] notification.send(SendDto): ReceiptDto.

export async function send(input: SendDto): Promise<ReceiptDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
