// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Confection } from "./mod.ts";

Deno.test("Confection.toDto", () => {
  // TODO: test toDto
});
