// Generated by rune manifest — DO NOT EDIT (regenerated on every `rune sync`).

// Domain nouns (from [NON]):
//   task: a single todo item
//
// Type vocabulary (from [TYP]):
//   id: string — a unique task identifier
//   title: string — the human-readable task title
//   done: boolean — whether the task has been completed
//
// Backing services (shared, from src/core/core.rune):
//   db (SIDECAR): DB_URL
// Public API surface for module "tasks".

export { create } from "./domain/coordinators/task-create/mod.ts";

export { complete } from "./domain/coordinators/task-complete/mod.ts";

