// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// input to create a new task
export const CreateTaskDtoSchema = z.object({

  title: z.unknown(), // TODO: tighten

});

export type CreateTaskDto = z.infer<typeof CreateTaskDtoSchema>;
