// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a unique task identifier
// rune declares: [TYP] id: string
export const idSchema = z.unknown(); // TODO: tighten to string
export type id = z.infer<typeof idSchema>;
