// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a persisted task record
export const TaskDtoSchema = z.object({

  id: z.unknown(), // TODO: tighten

  title: z.unknown(), // TODO: tighten

  done: z.unknown(), // TODO: tighten

});

export type TaskDto = z.infer<typeof TaskDtoSchema>;
