// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsBoolean, IsString } from "class-validator";

// a persisted task record
export class TaskDto {
  @IsString()
  id!: string;

  @IsString()
  title!: string;

  @IsBoolean()
  done!: boolean;
}
