// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a reference to an existing task
export const TaskRefDtoSchema = z.object({

  id: z.unknown(), // TODO: tighten

});

export type TaskRefDto = z.infer<typeof TaskRefDtoSchema>;
