// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// a reference to an existing task
export class TaskRefDto {
  @IsString()
  id!: string;
}
