// Generated by rune manifest from src/lists/lists.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { ListDto } from "@/src/lists/dto/list.ts";
import { DbService } from "@/src/core/data/db/mod.ts";

// Data adapter for `list` — the I/O boundary.
// Coordinators await these methods; implement each one.
// a named collection of tasks
export class List {
  constructor(private readonly db = new DbService()) {}
  /**
   * @param name the list name
   */
  fill(name: string): Promise<List> {
    throw new Error("not implemented");
  }
  /**
   * @param listDto a persisted list record
   * service: db (transport SIDECAR) — env: DB_URL
   * the project's primary datastore (sidecar)
   * @see https://docs.example.com/datastore
   * @throws timeout
   */
  save(listDto: ListDto): Promise<void> {
    throw new Error("not implemented");
  }
  /**
   * @returns a persisted list record
   */
  toDto(): Promise<ListDto> {
    throw new Error("not implemented");
  }
  /**
   * @param id a unique list identifier
   * @returns a persisted list record
   * service: db (transport SIDECAR) — env: DB_URL
   * the project's primary datastore (sidecar)
   * @see https://docs.example.com/datastore
   * @throws not-found
   */
  load(id: string): Promise<ListDto> {
    throw new Error("not implemented");
  }
  /**
   * @param taskId an id of a task placed on the list
   */
  append(taskId: string): Promise<List> {
    throw new Error("not implemented");
  }
}
