// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { ShopDto } from "@/src/cake/dto/shop.ts";
import type { CartDto } from "@/src/cake/dto/cart.ts";
import { Cart } from "@/src/cake/domain/business/cart/mod.ts";

// Coordinator for [REQ] cart.fill(ShopDto): CartDto.
export async function fill(input: ShopDto): Promise<CartDto> {

  // core — pure business logic, no I/O
  const out = fillCore(input);

  return out.result;
}

// Pure business logic for cart.fill — no I/O. Takes the
// request input; returns the result.
function fillCore(input: ShopDto): { result: CartDto } {
  const cart = new Cart();
  return { result: { cartId: `cart-${input.storeId}` } };
}
