// Load the Reflect polyfill once for every consumer — decorators (@Controller, @Module, …)
// need it at class-definition time, so importing the package is enough; apps don't have to
// remember their own `import "reflect-metadata"`.
import "#reflect-metadata";

export {
  appModule,
  Backend,
  BackendFrom,
  collectSetCookies,
  RequestJar,
  requestBoundClient,
  canonicalize,
  emitContractOpenApi,
  mergedOpenApiDoc,
  sha256Hex,
  stampSpecHash,
  BackendClient,
  bootstrapServer,
  buildMapModel,
  createBackendClient,
  createDocsJsonHandler,
  createKvTraceSink,
  createLimiter,
  DanetDocumentBuilder,
  DanetHttpAdapter,
  docsSeedScript,
  emulatorShellHtml,
  Endpoint,
  EndpointController,
  endpointModule,
  endpointsFromDoc,
  exerciseEndpoints,
  getProcessMetadata,
  getWsProcessMetadata,
  HttpAdapter,
  InjectClass,
  injectDocsScript,
  InjectFactory,
  InjectValue,
  INTERNAL_REQUEST_HEADER,
  KvTraceSink,
  log,
  Logger,
  mapShellHtml,
  MemoryTraceSink,
  orderedEndpoints,
  PROCESS_METADATA_KEY,
  processOrder,
  Server,
  setupWithSwagger,
  span,
  SwaggerDescription,
  swaggerShellHtml,
  Traced,
  Tracer,
  tracer,
  traceShellHtml,
  traceShipper,
  traceUser,
  withBasePath,
  WS_PROCESS_METADATA_KEY,
  WsEndpoint,
  WsEndpointController,
} from "@foundation/mod-root.ts";
// Rune assert runtime (also exported as the "./assert" subpath): seam
// validation for rune-generated code. bootstrapServer maps a thrown
// RuneAssertError to HTTP 422.
export { assert, RuneAssertError } from "../assert/mod.ts";
export type { Assert, AssertFailure } from "../assert/mod.ts";
export type {
  BackendOptions,
  BootedApi,
  BootstrapOptions,
  ComposedHandler,
  Frontend,
  DocsJsonHandlerOptions,
  EndpointMethod,
  EndpointOptions,
  EndpointResult,
  ExerciseAuth,
  ExerciseOptions,
  ExerciseReport,
  ExerciseTarget,
  FetchHandler,
  Limiter,
  LogLevel,
  MapEdge,
  MapLane,
  MapModel,
  MapNode,
  OpenApiDocument,
  OpenApiOperation,
  ProcessExtension,
  ProcessGraph,
  ProcessMetadata,
  ProcessOperation,
  RateLimitOptions,
  RequestContext,
  SeedOverrides,
  ServerDisposer,
  ServerLifecycle,
  Span,
  SpecEndpoint,
  SpecField,
  SpecParam,
  SwaggerDocEntry,
  Trace,
  TraceSink,
  WsEndpointOptions,
  WsProcessMetadata,
} from "@foundation/mod-root.ts";

export function safeStart(cb: () => Promise<void>): Promise<void> | undefined {
  if (import.meta.main) {
    return cb();
  }
}
