// Load the Reflect polyfill once for every consumer — decorators (@Controller, @Module, …)
// need it at class-definition time, so importing the package is enough; apps don't have to
// remember their own `import "reflect-metadata"`.
import "#reflect-metadata";

export {
  appModule,
  BackendClient,
  bootstrapServer,
  buildMapModel,
  createBackendClient,
  createCredentialGuard,
  createDocsJsonHandler,
  createInfraClient,
  createJwksVerifier,
  createKvTraceSink,
  createLimiter,
  createTokenAuthMiddleware,
  DanetDocumentBuilder,
  DanetHttpAdapter,
  docsSeedScript,
  emulatorShellHtml,
  Endpoint,
  EndpointController,
  endpointModule,
  endpointsFromDoc,
  exerciseEndpoints,
  getIdentity,
  getProcessMetadata,
  getWsProcessMetadata,
  Grant,
  Grants,
  GRANTS_METADATA_KEY,
  grantsForApp,
  HttpAdapter,
  IDENTITY_CONTEXT_KEY,
  InfraError,
  InjectClass,
  injectDocsScript,
  InjectFactory,
  InjectValue,
  INTERNAL_REQUEST_HEADER,
  isPublicContext,
  KvTraceSink,
  log,
  Logger,
  LoggedIn,
  mapShellHtml,
  MemoryTraceSink,
  noCodeCache,
  orderedEndpoints,
  PROCESS_METADATA_KEY,
  processOrder,
  Public,
  PUBLIC_METADATA_KEY,
  requiredGrants,
  resolveNetworkCredential,
  Server,
  SESSION_BEARER_CONTEXT_KEY,
  SESSION_BEARER_HEADER,
  setupWithSwagger,
  span,
  SwaggerDescription,
  swaggerShellHtml,
  TokenError,
  Traced,
  Tracer,
  tracer,
  traceShellHtml,
  traceShipper,
  traceUser,
  validateCredential,
  verifyToken,
  withBasePath,
  WS_PROCESS_METADATA_KEY,
  WsEndpoint,
  WsEndpointController,
} from "@foundation/mod-root.ts";
// Rune assert runtime (also exported as the "./assert" subpath): seam
// validation for rune-generated code. bootstrapServer maps a thrown
// RuneAssertError to HTTP 422.
export { assert, RuneAssertError } from "../assert/mod.ts";
export type { Assert, AssertFailure } from "../assert/mod.ts";
export type {
  CredentialGuardConfig,
  DanetGuard,
  DocsJsonHandlerOptions,
  EndpointMethod,
  EndpointOptions,
  EndpointResult,
  ExerciseAuth,
  ExerciseOptions,
  ExerciseReport,
  ExerciseTarget,
  FetchHandler,
  Identity,
  InfraClient,
  InfraClientConfig,
  InfraJwk,
  InfraJwks,
  JwksVerifierOptions,
  Limiter,
  LogLevel,
  MapEdge,
  MapLane,
  MapModel,
  MapNode,
  NoCodeCacheContext,
  NoCodeCacheMiddleware,
  NoCodeCacheOptions,
  OpenApiDocument,
  OpenApiOperation,
  ProcessExtension,
  ProcessGraph,
  ProcessMetadata,
  ProcessOperation,
  RateLimitOptions,
  RequestContext,
  ResolvedCredential,
  RevocationStatus,
  SeedOverrides,
  SessionBearerPayload,
  SessionVerifier,
  Span,
  SpecEndpoint,
  SpecField,
  SpecParam,
  SwaggerDocEntry,
  TokenAuthConfig,
  Trace,
  TraceSink,
  WsEndpointOptions,
  WsProcessMetadata,
} from "@foundation/mod-root.ts";

export function safeStart(cb: () => Promise<void>): Promise<void> | undefined {
  if (import.meta.main) {
    return cb();
  }
}
