// Load the Reflect polyfill once for every consumer — decorators (@Controller, @Module, …)
// need it at class-definition time, so importing the package is enough; apps don't have to
// remember their own `import "reflect-metadata"`.
import "#reflect-metadata";

export {
  appModule,
  auditRoutes,
  BackendClient,
  bootstrapServer,
  buildMapModel,
  createBackendClient,
  createCredentialGuard,
  createDocsJsonHandler,
  createInfraClient,
  createJwksVerifier,
  createKvSessionStore,
  createKvTraceSink,
  createLimiter,
  createMemorySessionStore,
  createTokenAuthMiddleware,
  DanetDocumentBuilder,
  DanetHttpAdapter,
  decodeBearer,
  DEFAULT_REFRESH_SKEW_SECONDS,
  docsSeedScript,
  emulatorShellHtml,
  Endpoint,
  EndpointController,
  endpointModule,
  endpointsFromDoc,
  exerciseEndpoints,
  getIdentity,
  getProcessMetadata,
  getWsProcessMetadata,
  Grant,
  Grants,
  GRANTS_METADATA_KEY,
  grantsForApp,
  HttpAdapter,
  IDENTITY_CONTEXT_KEY,
  InfraError,
  InjectClass,
  injectDocsScript,
  InjectFactory,
  InjectValue,
  InProcessOnly,
  intakeSession,
  Internal,
  INTERNAL_METADATA_KEY,
  INTERNAL_REQUEST_HEADER,
  isInternalContext,
  isPublicContext,
  KvSessionStore,
  KvTraceSink,
  log,
  LoggedIn,
  Logger,
  mapShellHtml,
  MemoryTraceSink,
  openRoutes,
  orderedEndpoints,
  PROCESS_METADATA_KEY,
  processOrder,
  Public,
  PUBLIC_METADATA_KEY,
  readCookie,
  requiredGrants,
  resolveNetworkCredential,
  resolveSession,
  Server,
  SESSION_COOKIE_NAME,
  sessionExpiryOf,
  setupWithSwagger,
  span,
  SwaggerDescription,
  swaggerShellHtml,
  TokenError,
  Traced,
  Tracer,
  tracer,
  traceShellHtml,
  traceShipper,
  traceUser,
  validateCredential,
  verifyToken,
  warnOpenRoutes,
  withBasePath,
  WS_PROCESS_METADATA_KEY,
  WsEndpoint,
  WsEndpointController,
} from "@foundation/mod-root.ts";
// Rune assert runtime (also exported as the "./assert" subpath): seam
// validation for rune-generated code. bootstrapServer maps a thrown
// RuneAssertError to HTTP 422.
export { assert, RuneAssertError } from "../assert/mod.ts";
export type { Assert, AssertFailure } from "../assert/mod.ts";
export type {
  AuthExchange,
  BootstrapOptions,
  CredentialGuardConfig,
  CredentialKind,
  DanetGuard,
  DecodedBearer,
  DocsJsonHandlerOptions,
  EndpointMethod,
  EndpointOptions,
  EndpointResult,
  ExchangeEnvelope,
  ExerciseAuth,
  ExerciseOptions,
  ExerciseReport,
  ExerciseTarget,
  FetchHandler,
  Identity,
  InfraClient,
  InfraClientConfig,
  InfraJwk,
  InfraJwks,
  IntakeInput,
  IntakeResult,
  JwksVerifierOptions,
  Limiter,
  LogLevel,
  MapEdge,
  MapLane,
  MapModel,
  MapNode,
  NewSession,
  OpenApiDocument,
  OpenApiOperation,
  ProcessExtension,
  ProcessGraph,
  ProcessMetadata,
  ProcessOperation,
  RateLimitOptions,
  RequestContext,
  ResolvedCredential,
  ResolveOptions,
  RevocationStatus,
  RouteAuditEntry,
  RoutePosture,
  SeedOverrides,
  ServerDisposer,
  ServerLifecycle,
  SessionBearerPayload,
  SessionExchange,
  SessionProfile,
  SessionRecord,
  SessionResolver,
  SessionStore,
  SessionVerifier,
  Span,
  SpecEndpoint,
  SpecField,
  SpecParam,
  SwaggerDocEntry,
  TokenAuthConfig,
  Trace,
  TraceSink,
  WarnOpenRoutesOptions,
  WsEndpointOptions,
  WsProcessMetadata,
} from "@foundation/mod-root.ts";

export function safeStart(cb: () => Promise<void>): Promise<void> | undefined {
  if (import.meta.main) {
    return cb();
  }
}
