// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { ChannelBase } from "@/src/notify/domain/business/channel/base/mod.ts";

// Variant: Email

export default class ChannelEmail extends ChannelBase {
  deliver(sendDto: unknown): unknown {
    throw new Error("not implemented");
  }
}
