// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import ChannelEmail from "./mod.ts";

Deno.test("Channel/Email — placeholder", () => {
  // TODO: variant-specific tests
});
