// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { OrderDto } from "@/src/checkout/dto/order.ts";

// Data adapter for `order` — the I/O boundary.
// Coordinators await these methods; implement each one.
export class Order {
  /**
   * @param orderDto a created order
   * service: db (no [SRV] declared)
   * @throws timeout
   */
  save(orderDto: OrderDto): Promise<void> {
    throw new Error("not implemented");
  }
}
