// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Boundary methods to reach:
//   Order.save(OrderDto) (service: db)

Deno.test("order — connectivity", () => {
  // TODO: smoke test that verifies the boundary is reachable
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

