// Generated by rune manifest — DO NOT EDIT (regenerated on every `rune sync`).

// Domain nouns (from [NON]):
//   notification: a queued outbound notification
//   channel: a delivery channel (email or push)
//
// Type vocabulary (from [TYP]):
//   id: string — a unique notification id
//   message: string — the notification body text
//   status: string — the delivery status of the notification
//
// Backing services (shared, from src/core/core.rune):
//   ex (HTTP): EX_BASE_URL
// Public API surface for module "notify".

export { send } from "./domain/coordinators/notification-send/mod.ts";

