// Build step — stamps the rune binary's identity into a generated module.
//
//   deno run --allow-read --allow-run --allow-write scripts/gen-version.ts
//
// Writes src/core/dto/version.gen.ts (gitignored, like lsp-config.ts) with:
//   - RUNE_VERSION: the project's semver, read from keep/deno.json (the value
//     the "release: vX.Y.Z (auto-bump)" commits bump). Shown by `rune -v`.
//   - RUNE_COMMIT:  the commit this binary was built from. rune ships as a
//     ROLLING `latest` release (no semver tag on the binary), so the only
//     reliable "is my binary stale" signal is comparing this baked commit
//     against the commit the `latest` release tag points at. In CI the
//     release is cut from GITHUB_SHA and gh-release moves the `latest` tag to
//     that same commit, so a fresh install's RUNE_COMMIT == tags/latest sha
//     (no false nag); once main advances and a new release is cut, older
//     binaries see a mismatch and `rune -v` reports a newer version.
//
// `deno compile` snapshots this file into the binary, so the fetch-and-compare
// in `rune -v` runs against a baked, build-time identity — not the user's repo.

const OUT = "src/core/dto/version.gen.ts";

function version(): string {
  // CI stamps the exact release version it is about to cut (the `release-rune`
  // workflow's `version` job), so a `vX.Y.Z` release and the binary's `rune -v`
  // never disagree. The leading `v` is optional. Locally this is unset and we
  // fall back to keep/deno.json (the canonical semver the JSR auto-bump moves).
  const override = Deno.env.get("RUNE_VERSION_OVERRIDE");
  if (override && override.trim()) return override.trim().replace(/^v/, "");
  try {
    const { version } = JSON.parse(Deno.readTextFileSync("keep/deno.json"));
    if (typeof version === "string" && version) return version;
  } catch { /* fall through */ }
  return "unknown";
}

function commit(): string {
  // CI builds the release from GITHUB_SHA — prefer it so the baked commit
  // matches what gh-release will point `latest` at. Locally, ask git.
  const env = Deno.env.get("GITHUB_SHA");
  if (env) return env.trim();
  try {
    const { stdout, code } = new Deno.Command("git", {
      args: ["rev-parse", "HEAD"],
      stdout: "piped",
      stderr: "null",
    }).outputSync();
    if (code === 0) return new TextDecoder().decode(stdout).trim();
  } catch { /* fall through */ }
  return "unknown";
}

if (import.meta.main) {
  // `: string` keeps the values from narrowing to literal types, so the
  // `=== "unknown"` guards in version/mod.ts stay legal comparisons.
  const content = `// AUTO-GENERATED by scripts/gen-version.ts — do not edit
export const RUNE_VERSION: string = ${JSON.stringify(version())};
export const RUNE_COMMIT: string = ${JSON.stringify(commit())};
`;
  Deno.writeTextFileSync(OUT, content);
  console.log(`Version: ${version()} (${commit().slice(0, 7)})`);
}
