// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Delivery } from "./mod.ts";

Deno.test("Delivery.toDto", () => {
  // TODO: test toDto
});
