// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Endpoint, EndpointController, endpointModule } from "@mrg-keystone/keep";
import { StartDto } from "@/src/checkout/dto/start.ts";
import { TicketDto } from "@/src/checkout/dto/ticket.ts";
import { PayDto } from "@/src/checkout/dto/pay.ts";
import { PaymentDto } from "@/src/checkout/dto/payment.ts";
import { FulfillDto } from "@/src/checkout/dto/fulfill.ts";
import { DoneDto } from "@/src/checkout/dto/done.ts";
import { SurveyDto } from "@/src/checkout/dto/survey.ts";
import { ThanksDto } from "@/src/checkout/dto/thanks.ts";
import { open as ticketOpen } from "@/src/checkout/domain/coordinators/ticket-open/mod.ts";
import { charge as paymentCharge } from "@/src/checkout/domain/coordinators/payment-charge/mod.ts";
import { complete as deliveryComplete } from "@/src/checkout/domain/coordinators/delivery-complete/mod.ts";
import { collect as feedbackCollect } from "@/src/checkout/domain/coordinators/feedback-collect/mod.ts";

@EndpointController("http")
export class HttpController {
  @Endpoint({ path: "start", input: StartDto, output: TicketDto, order: 1, bind: {"memberId":"$memberId"} })
  start(body: StartDto): Promise<TicketDto> {
    return ticketOpen(body);
  }

  @Endpoint({ path: "pay-card", input: PayDto, output: PaymentDto, order: 2, dependsOn: ["start"], bind: {"ticketId":"start.ticketId"}, flows: "card" })
  payCard(body: PayDto): Promise<PaymentDto> {
    return paymentCharge(body);
  }

  @Endpoint({ path: "pay-cash", input: PayDto, output: PaymentDto, order: 3, dependsOn: ["start"], bind: {"ticketId":"start.ticketId"}, flows: "cash" })
  payCash(body: PayDto): Promise<PaymentDto> {
    return paymentCharge(body);
  }

  @Endpoint({ path: "fulfill", input: FulfillDto, output: DoneDto, order: 4, dependsOn: ["payCard","payCash"], bind: {"paymentId":["payCard.paymentId","payCash.paymentId"]} })
  fulfill(body: FulfillDto): Promise<DoneDto> {
    return deliveryComplete(body);
  }

  @Endpoint({ path: "survey", input: SurveyDto, output: ThanksDto, order: 5, optional: true })
  survey(body: SurveyDto): Promise<ThanksDto> {
    return feedbackCollect(body);
  }
}

export const httpModule = endpointModule("Checkout", [HttpController]);
