// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// minted by the members module
// rune declares: [TYP] memberId: string
export type MemberId = string;
