// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// whether the survey was acknowledged
// rune declares: [TYP] thanked: boolean
export type Thanked = boolean;
