// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// the opened checkout ticket
export class TicketDto {
  @IsString()
  ticketId!: string;
}
