// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a checkout ticket identifier
// rune declares: [TYP] ticketId: string
export type TicketId = string;
