// Generated by rune manifest from spec/runes/tasks.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { TaskDto } from "@/src/tasks/dto/task.ts";

// a single todo item
export class Task {
  id: string = "";
  title: string = "";
  done: boolean = false;

  /**
   * @param title the human-readable task title
   */
  fill(title: string): Task {
    this.title = title;
    return this;
  }
  /**
   * @param taskDto a persisted task record
   * @throws timeout
   */
  save(taskDto: TaskDto): void {
    throw new Error("not implemented");
  }
  /**
   * @returns a persisted task record
   */
  toDto(): TaskDto {
    return Object.assign(new TaskDto(), { id: this.id, title: this.title, done: this.done });
  }
  /**
   * @param id a unique task identifier
   * @returns a persisted task record
   * @throws not-found
   */
  load(id: string): TaskDto {
    throw new Error("not implemented");
  }
  markDone(): Task {
    this.done = true;
    return this;
  }
}
