// Generated by rune manifest from spec/runes/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.
// Task: a single todo item

import { assertEquals } from "#std/assert";
import { Task } from "./mod.ts";

Deno.test("Task.fill", () => {
  // Arrange
  const subject = new Task();
  // Act — fill(title): task — must return a Task whose title equals the supplied string
  const result = subject.fill("buy milk");
  // Assert
  // deno-lint-ignore no-explicit-any
  assertEquals((result as any).title, "buy milk");
});

Deno.test("Task.markDone", () => {
  // Arrange
  const subject = new Task();
  // Act — markDone(): task — must return a Task with done === true
  const result = subject.markDone();
  // Assert
  // deno-lint-ignore no-explicit-any
  assertEquals((result as any).done, true);
});

Deno.test("Task.toDto", () => {
  // Arrange — a task whose internal state is known
  const subject = Object.assign(new Task(), { id: "task-1", title: "buy milk", done: false });
  // Act — toDto(): TaskDto — must mirror id, title, done from the task
  const dto = subject.toDto();
  // Assert
  assertEquals(dto.id, "task-1");
  assertEquals(dto.title, "buy milk");
  assertEquals(dto.done, false);
});
