// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { NewOrderDto } from "@/src/checkout/dto/new-order.ts";
import { OrderDto } from "@/src/checkout/dto/order.ts";
import { assert } from "#assert";
import { Order } from "@/src/checkout/domain/business/order/mod.ts";
import { Order as OrderData } from "@/src/checkout/domain/data/order/mod.ts";

// Coordinator for [REQ] order.create(NewOrderDto): OrderDto.
export async function create(input: NewOrderDto): Promise<OrderDto> {
  const validInput = assert(NewOrderDto, input, "order.create input");
  const orderData = new OrderData();

  // core — pure business logic, no I/O
  const out = createCore(validInput);

  // writes — side effects through the data adapters (validated before they leave)
  await orderData.save(assert(OrderDto, out.save, "order.save input"));

  return assert(OrderDto, out.result, "order.create output");
}

// Pure business logic for order.create — no I/O. Takes the
// request input; returns the dtos the writes consume plus the result.
function createCore(input: NewOrderDto): { save: OrderDto; result: OrderDto } {
  const order = new Order();
  // TODO: run the pure steps on order, build the dtos
  throw new Error("not implemented");
}
