// Generated by rune manifest from corpus/valid/entrypoint.rune:6.
// Edit the body. Re-running manifest will not overwrite this file.

import { NewOrderDto } from "@/src/checkout/dto/new-order.ts";
import { OrderDto } from "@/src/checkout/dto/order.ts";
import { assert } from "#assert";
import { Order as OrderData } from "@/src/checkout/domain/data/order/mod.ts";

/**
 * Coordinator for [REQ] order.create(NewOrderDto): OrderDto.
 * @param input NewOrderDto — asserted against its contract at the seam.
 * @returns OrderDto — asserted before return.
 * @throws timeout — raised by order.save
 */
export async function create(input: NewOrderDto): Promise<OrderDto> {
  const validInput = assert(NewOrderDto, input, "order.create input");
  const orderData = new OrderData();

  // core — pure business logic, no I/O
  const out = createCore(validInput);

  // after the core — boundary calls in spec order (validated at the seam)
  // (guards run in the core above: a throw there prevents every call below)
  await orderData.save(assert(OrderDto, out.save, "order.save input"));

  return assert(OrderDto, out.result, "order.create output");
}

// Pure business logic for order.create — no I/O. Takes the
// request input; returns the dtos the writes consume plus the result.
function createCore(input: NewOrderDto): { save: OrderDto; result: OrderDto } {
  // Recipe from [REQ] order.create (run in order):
  //   1. [RET] OrderDto
  // TODO: implement the steps above, then build the dtos
  throw new Error("not implemented");
}
