// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Endpoint, EndpointController, endpointModule } from "@mrg-keystone/rune";
import { DriveDto } from "@/src/cake/dto/drive.ts";
import { ArrivalDto } from "@/src/cake/dto/arrival.ts";
import { ShopDto } from "@/src/cake/dto/shop.ts";
import { CartDto } from "@/src/cake/dto/cart.ts";
import { CheckoutDto } from "@/src/cake/dto/checkout.ts";
import { ReceiptDto } from "@/src/cake/dto/receipt.ts";
import { MixDto } from "@/src/cake/dto/mix.ts";
import { BatterDto } from "@/src/cake/dto/batter.ts";
import { BakeDto } from "@/src/cake/dto/bake.ts";
import { CakeDto } from "@/src/cake/dto/cake.ts";
import { CutDto } from "@/src/cake/dto/cut.ts";
import { SlicesDto } from "@/src/cake/dto/slices.ts";
import { reach as arrivalReach } from "@/src/cake/domain/coordinators/arrival-reach/mod.ts";
import { fill as cartFill } from "@/src/cake/domain/coordinators/cart-fill/mod.ts";
import { pay as receiptPay } from "@/src/cake/domain/coordinators/receipt-pay/mod.ts";
import { mix as batterMix } from "@/src/cake/domain/coordinators/batter-mix/mod.ts";
import { bake as confectionBake } from "@/src/cake/domain/coordinators/confection-bake/mod.ts";
import { cut as slicesCut } from "@/src/cake/domain/coordinators/slices-cut/mod.ts";

@EndpointController("http")
export class HttpController {
  @Endpoint({ path: "drive-to-store", input: DriveDto, output: ArrivalDto, order: 1 })
  driveToStore(body: DriveDto): Promise<ArrivalDto> {
    return arrivalReach(body);
  }

  @Endpoint({ path: "grocery-shop", input: ShopDto, output: CartDto, order: 2, dependsOn: ["driveToStore"], bind: {"storeId":"driveToStore.storeId"} })
  groceryShop(body: ShopDto): Promise<CartDto> {
    return cartFill(body);
  }

  @Endpoint({ path: "checkout", input: CheckoutDto, output: ReceiptDto, order: 3, dependsOn: ["groceryShop"], bind: {"cartId":"groceryShop.cartId"} })
  checkout(body: CheckoutDto): Promise<ReceiptDto> {
    return receiptPay(body);
  }

  @Endpoint({ path: "mix-ingredients", input: MixDto, output: BatterDto, order: 4, dependsOn: ["checkout"], bind: {"ingredientsId":"checkout.ingredientsId"} })
  mixIngredients(body: MixDto): Promise<BatterDto> {
    return batterMix(body);
  }

  @Endpoint({ path: "bake", input: BakeDto, output: CakeDto, order: 5, dependsOn: ["mixIngredients"], bind: {"batterId":"mixIngredients.batterId"} })
  bake(body: BakeDto): Promise<CakeDto> {
    return confectionBake(body);
  }

  @Endpoint({ path: "cut", input: CutDto, output: SlicesDto, order: 6, dependsOn: ["bake"], bind: {"cakeId":"bake.cakeId"} })
  cut(body: CutDto): Promise<SlicesDto> {
    return slicesCut(body);
  }
}

export const httpModule = endpointModule("Cake", [HttpController]);
