// Generated by shape-checker manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// an order to place
export const PlaceOrderDtoSchema = z.object({

  items: z.unknown(), // TODO: tighten

});

export type PlaceOrderDto = z.infer<typeof PlaceOrderDtoSchema>;
