// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import "reflect-metadata";
import { Type } from "class-transformer";
import { ValidateNested } from "class-validator";

// a receipt for a payment
export class ReceiptDto {
  @ValidateNested()
  @Type(() => ReceiptDto)
  receipt!: ReceiptDto;
}
