// Generated by rune manifest from corpus/valid/entrypoint.rune:29.
// Edit the body. Re-running manifest will not overwrite this file.

/** the receipt code */
// rune declares: [TYP] receipt: string
export type Receipt = string;
