// Generated by rune manifest from corpus/valid/module-billing.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { InvoiceDto } from "@/src/billing/dto/invoice.ts";
import { IssueDto } from "@/src/billing/dto/issue.ts";

// Data adapter for `invoice` — the I/O boundary.
// Coordinators await these methods; implement each one.
export class Invoice {
  /**
   * @param issueDto a request to issue an invoice
   * @returns an issued invoice
   * service: db (transport SIDECAR) — env: DB_URL
   * the primary datastore
   * @see https://docs.example.com/db
   * @throws timeout
   */
  save(issueDto: IssueDto): Promise<InvoiceDto> {
    throw new Error("not implemented");
  }
}
