// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { PayDto } from "@/src/checkout/dto/pay.ts";
import type { PaymentDto } from "@/src/checkout/dto/payment.ts";
import { Payment } from "@/src/checkout/domain/business/payment/mod.ts";

// Coordinator for [REQ] payment.charge(PayDto): PaymentDto.
export async function charge(input: PayDto): Promise<PaymentDto> {

  // core — pure business logic, no I/O
  const out = chargeCore(input);

  return out.result;
}

// Pure business logic for payment.charge — no I/O. Takes the
// request input; returns the result.
function chargeCore(input: PayDto): { result: PaymentDto } {
  const _payment = new Payment();
  if (!input.ticketId) {
    throw new Error("missing ticketId — chaining did not happen");
  }
  return { result: { paymentId: `pay-${input.ticketId}` } };
}
