// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { SendDto } from "@/src/notify/dto/send.ts";
import { ReceiptDto } from "@/src/notify/dto/receipt.ts";
import { assert } from "#assert";
import { Notification } from "@/src/notify/domain/business/notification/mod.ts";

// Coordinator for [REQ] notification.send(SendDto): ReceiptDto.
export async function send(input: SendDto): Promise<ReceiptDto> {
  const validInput = assert(SendDto, input, "notification.send input");

  // core — pure business logic, no I/O
  const out = sendCore(validInput);

  return assert(ReceiptDto, out.result, "notification.send output");
}

// Pure business logic for notification.send — no I/O. Takes the
// request input; returns the result.
function sendCore(input: SendDto): { result: ReceiptDto } {
  const notification = new Notification();
  // TODO: run the pure steps on notification, build the dtos
  throw new Error("not implemented");
}
