// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { httpModule } from "./mod.ts";
import { bootstrapServer, exerciseEndpoints } from "@mrg-keystone/rune";
import { assertEquals } from "#std/assert";

// Fill the coordinator bodies, then run with RUNE_E2E=1 to drive every endpoint
// to green (orders by @Endpoint order, chains outputs into inputs via bind).
Deno.test({
  name: "tasks/http — endpoints run and chain",
  ignore: !Deno.env.get("RUNE_E2E"),
  fn: async () => {
    const api = await bootstrapServer("tasks", httpModule, { swagger: true });
    try {
      // $ext seeds — replace stub values with real inputs:
      //   id — a unique task identifier
      // Endpoint chain (by @Endpoint order):
      //   1. add -> TaskDto (after finish)
      //   2. finish -> TaskDto
      const report = await exerciseEndpoints({ api, overrides: { seeds: { id: "id-stub" } } });
      assertEquals(report.failed.map((r) => r.id), []);
    } finally {
      await api.stop();
    }
  },
});
