// Generated by rune manifest from src/tasks/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Endpoint, EndpointController, endpointModule } from "@mrg-keystone/rune";
import { CreateTaskDto } from "@/src/tasks/dto/create-task.ts";
import { TaskDto } from "@/src/tasks/dto/task.ts";
import { CompleteTaskDto } from "@/src/tasks/dto/complete-task.ts";
import { create as taskCreate } from "@/src/tasks/domain/coordinators/task-create/mod.ts";
import { complete as taskComplete } from "@/src/tasks/domain/coordinators/task-complete/mod.ts";

@EndpointController("http")
export class HttpController {
  /**
   * Delegates to coordinator task.create (matched by input/output signature).
   * @param body CreateTaskDto — input to create a new task
   * @returns TaskDto — a persisted task record
   * @throws timeout (task.save)
   */
  // title <- finish.title
  // Runs after: finish.
  // from src/tasks/tasks.rune:19
  @Endpoint({ path: "add", input: CreateTaskDto, output: TaskDto, order: 1, dependsOn: ["finish"], bind: {"title":"finish.title"} })
  add(body: CreateTaskDto): Promise<TaskDto> {
    return taskCreate(body);
  }

  /**
   * Delegates to coordinator task.complete (matched by input/output signature).
   * @param body CompleteTaskDto — a reference to the task to complete
   * @returns TaskDto — a persisted task record
   * @throws not-found (task.load)
   * @throws timeout (task.save)
   */
  // id <- supplied externally (seed / module input)
  // from src/tasks/tasks.rune:21
  @Endpoint({ path: "finish", input: CompleteTaskDto, output: TaskDto, order: 2, bind: {"id":"$id"} })
  finish(body: CompleteTaskDto): Promise<TaskDto> {
    return taskComplete(body);
  }
}

export const httpModule = endpointModule("Tasks", [HttpController]);
