// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// the store you arrived at
export class ArrivalDto {
  @IsString()
  storeId!: string;
}
