// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// the mixed batter
export class BatterDto {
  @IsString()
  batterId!: string;
}
