// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a mixed-batter identifier
// rune declares: [TYP] batterId: string
export type BatterId = string;
