// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// the cart to check out
export class CheckoutDto {
  @IsString()
  cartId!: string;
}
