// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a place to drive to
// rune declares: [TYP] destination: string
export type Destination = string;
