// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// where to drive to buy ingredients
export class DriveDto {
  @IsString()
  destination!: string;
}
