// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a purchased-ingredients identifier
// rune declares: [TYP] ingredientsId: string
export type IngredientsId = string;
