// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsNumber } from "class-validator";

// how many slices the cake yielded
export class SlicesDto {
  @IsNumber()
  sliceCount!: number;
}
