// Generated by rune manifest from src/cake/cake.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a grocery store identifier
// rune declares: [TYP] storeId: string
export type StoreId = string;
