// Generated by rune manifest from spec/runes/tasks.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { complete } from "./mod.ts";
import { create } from "@/src/tasks/domain/coordinators/task-create/mod.ts";
import { CompleteTaskDto } from "@/src/tasks/dto/complete-task.ts";
import { CreateTaskDto } from "@/src/tasks/dto/create-task.ts";
import { DbService } from "@/src/core/data/db/mod.ts";
import { assertEquals, assertRejects } from "#std/assert";

async function seedTask(title: string): Promise<string> {
  const created = await create(Object.assign(new CreateTaskDto(), { title }));
  return created.id;
}

function ref(id: string): CompleteTaskDto {
  return Object.assign(new CompleteTaskDto(), { id });
}

// Happy path: load the seeded task, markDone, save, return done=true.
Deno.test("complete — happy path", async () => {
  const id = await seedTask("finish");
  const result = await complete(ref(id));
  assertEquals(result.id, id);
  assertEquals(result.title, "finish");
  assertEquals(result.done, true);
});

// The `not-found` fault from the db load boundary propagates out of complete().
Deno.test("not-found", async () => {
  await assertRejects(
    () => complete(ref("missing-" + crypto.randomUUID())),
    Error,
    "not-found",
  );
});

// The `timeout` fault from the db save boundary propagates out of complete()
// (load succeeds first, then the save write fails).
Deno.test("timeout", async () => {
  const id = await seedTask("will time out");
  DbService.failNextPut = "timeout";
  await assertRejects(() => complete(ref(id)), Error, "timeout");
});
