// Generated by rune manifest from spec/runes/tasks.rune:11.
// Edit the body. Re-running manifest will not overwrite this file.

import { CompleteTaskDto } from "@/src/tasks/dto/complete-task.ts";
import { TaskDto } from "@/src/tasks/dto/task.ts";
import { assert } from "#assert";
import { Task } from "@/src/tasks/domain/business/task/mod.ts";
import { Task as TaskData } from "@/src/tasks/domain/data/task/mod.ts";

/**
 * Coordinator for [REQ] task.complete(CompleteTaskDto): TaskDto.
 * @param input CompleteTaskDto — asserted against its contract at the seam.
 * @returns TaskDto — asserted before return.
 * @throws not-found — raised by task.load
 * @throws timeout — raised by task.save
 */
export async function complete(input: CompleteTaskDto): Promise<TaskDto> {
  const validInput = assert(CompleteTaskDto, input, "task.complete input");
  const taskData = new TaskData();

  // reads — load inputs through the data adapters (validated at the seam)
  const taskLoad = assert(TaskDto, await taskData.load(validInput.id), "task.load");

  // core — pure business logic, no I/O
  const out = completeCore(validInput, taskLoad);

  // writes — side effects through the data adapters (validated before they leave)
  await taskData.save(assert(TaskDto, out.save, "task.save input"));

  return assert(TaskDto, out.result, "task.complete output");
}

// Pure business logic for task.complete — no I/O. Takes the
// request input and the dtos the reads loaded; returns the dtos the writes consume plus the result.
function completeCore(input: CompleteTaskDto, taskLoad: TaskDto): { save: TaskDto; result: TaskDto } {
  // Recipe from [REQ] task.complete: markDone → toDto. Rehydrate the loaded task,
  // mark it done, project back to a dto.
  const task = new Task();
  task.id = taskLoad.id;
  task.title = taskLoad.title;
  task.done = taskLoad.done;
  task.markDone();
  const dto = task.toDto();
  return { save: dto, result: dto };
}
