// Generated by rune manifest from spec/runes/notes.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { NoteDto } from "@/src/notes/dto/note.ts";
import { DbService } from "@/src/core/data/db/mod.ts";

// Data adapter for `note` — the I/O boundary.
// Coordinators await these methods; implement each one.
// a single note
export class Note {
  constructor(private readonly db = new DbService()) {}
  /**
   * @param body the note body text
   */
  fill(body: string): Promise<Note> {
    throw new Error("not implemented");
  }
  /**
   * @param noteDto a persisted note record
   * service: db (transport SIDECAR) — env: DB_URL
   * the app's datastore boundary
   * @see https://example.com/db
   * @throws timeout
   */
  save(noteDto: NoteDto): Promise<void> {
    throw new Error("not implemented");
  }
  /**
   * @returns a persisted note record
   */
  toDto(): Promise<NoteDto> {
    throw new Error("not implemented");
  }
  /**
   * @param id a unique note identifier
   * @returns a persisted note record
   * service: db (transport SIDECAR) — env: DB_URL
   * the app's datastore boundary
   * @see https://example.com/db
   * @throws not-found
   */
  load(id: string): Promise<NoteDto> {
    throw new Error("not implemented");
  }
  markArchived(): Promise<Note> {
    throw new Error("not implemented");
  }
}
