// Generated by rune manifest from spec/runes/notes.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Boundary methods to reach:
//   Note.fill(body)
//   Note.save(NoteDto) (service: db)
//   Note.toDto()
//   Note.load(id) (service: db)
//   Note.markArchived()

Deno.test("note — connectivity", () => {
  // TODO: smoke test that verifies the boundary is reachable
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});


Deno.test("not-found", async () => {
  // TODO: assert this fault path
});

