// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Payment } from "./mod.ts";

Deno.test("Payment.toDto", () => {
  // TODO: test toDto
});
