// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the notification body text
// rune declares: [TYP] message: string
export type Message = string;
