// Generated by rune manifest from src/notify/notify.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// input to send a notification
export class SendDto {
  @IsString()
  message!: string;
}
