// Generated by rune manifest from src/core/core.rune.
// Shared service client. Scaffolded once; fill in the body. `sync` preserves this file.

/**
 * ex (transport hp) — env: EX_BASE_URL
 * an external HTTP service
 * @see https://example.com/api/docs
 */
export class ExService {
  // Wire this client from env: EX_BASE_URL
}
