// Generated by rune manifest from src/core/core.rune.
// Edit the body. Re-running manifest will not overwrite this file.

Deno.test("ex — connectivity", () => {
  // TODO: smoke test that ExService can reach ex (transport hp)
});
