// Generated by rune manifest from src/core/core.rune.
// Shared service client. Scaffolded once; fill in the body. `sync` preserves this file.

/**
 * db (transport SIDECAR) — env: DB_URL
 * the project's primary datastore (sidecar)
 * @see https://docs.example.com/datastore
 */
export class DbService {
  // Wire this client from env: DB_URL
}
