// Generated by rune manifest from src/core/core.rune.
// Edit the body. Re-running manifest will not overwrite this file.

Deno.test("db — connectivity", () => {
  // TODO: smoke test that DbService can reach db (transport sc)
});
