// Generated by shape-checker manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Entrypoint surface: http.

export async function placeOrder(input: PlaceOrderDto): Promise<ReceiptDto> {
  // TODO: dispatch to the corresponding [REQ] coordinator.
  throw new Error("not implemented");
}
