// Load the Reflect polyfill once for every consumer — decorators (@Controller, @Module, …)
// need it at class-definition time, so importing the package is enough; apps don't have to
// remember their own `import "reflect-metadata"`.
import "#reflect-metadata";

export {
  appModule,
  BackendClient,
  bootstrapServer,
  buildMapModel,
  createBackendClient,
  createCredentialGuard,
  createDocsJsonHandler,
  createFirebaseVerifier,
  createLimiter,
  createMintUi,
  createTokenAuthMiddleware,
  DanetDocumentBuilder,
  DanetHttpAdapter,
  docsSeedScript,
  embed,
  emulatorShellHtml,
  Endpoint,
  EndpointController,
  endpointModule,
  endpointsFromDoc,
  exerciseEndpoints,
  FirebaseAuthError,
  getIdentity,
  getProcessMetadata,
  HttpAdapter,
  IDENTITY_CONTEXT_KEY,
  InjectClass,
  injectDocsScript,
  InjectFactory,
  InjectValue,
  INTERNAL_REQUEST_HEADER,
  isLocalRequest,
  isPublicContext,
  log,
  Logger,
  mapShellHtml,
  noCodeCache,
  orderedEndpoints,
  PROCESS_METADATA_KEY,
  processOrder,
  Public,
  PUBLIC_METADATA_KEY,
  requiredRoles,
  Roles,
  ROLES_METADATA_KEY,
  scopeRoles,
  Server,
  setupWithSwagger,
  signToken,
  SwaggerDescription,
  swaggerShellHtml,
  TokenError,
  verifyToken,
  withBasePath,
} from "@foundation/mod-root.ts";
// Rune assert runtime (also exported as the "./assert" subpath): seam
// validation for rune-generated code. bootstrapServer maps a thrown
// RuneAssertError to HTTP 422.
export { assert, RuneAssertError } from "../assert/mod.ts";
export type { Assert, AssertFailure } from "../assert/mod.ts";
export type {
  CredentialGuardConfig,
  DanetGuard,
  DocsJsonHandlerOptions,
  EmbedContext,
  EmbeddableBackend,
  EndpointMethod,
  EndpointOptions,
  EndpointResult,
  ExerciseAuth,
  ExerciseOptions,
  ExerciseReport,
  ExerciseTarget,
  FetchHandler,
  FirebaseClaims,
  FirebaseVerifier,
  FirebaseVerifierOptions,
  Identity,
  KeepState,
  Limiter,
  LogLevel,
  MapEdge,
  MapLane,
  MapModel,
  MapNode,
  MintUiConfig,
  NoCodeCacheContext,
  NoCodeCacheMiddleware,
  NoCodeCacheOptions,
  OpenApiDocument,
  OpenApiOperation,
  ProcessExtension,
  ProcessGraph,
  ProcessMetadata,
  ProcessOperation,
  RateLimitOptions,
  RequestContext,
  SeedOverrides,
  SpecEndpoint,
  SpecField,
  SpecParam,
  SwaggerDocEntry,
  TokenAuthConfig,
  TokenPayload,
} from "@foundation/mod-root.ts";

export function safeStart(cb: () => Promise<void>): Promise<void> | undefined {
  if (import.meta.main) {
    return cb();
  }
}
