export {
  Server,
  DanetHttpAdapter,
  HttpAdapter,
  SwaggerDescription,
  setupWithSwagger,
  DanetDocumentBuilder,
  bootstrapServer,
  InjectValue,
  InjectFactory,
  InjectClass,
  BackendClient,
  createBackendClient,
  log,
  Logger,
  signToken,
  verifyToken,
  TokenError,
  createTokenAuthMiddleware,
  createMintUi,
  isLocalRequest,
  withBasePath,
  INTERNAL_REQUEST_HEADER,
  createFirebaseVerifier,
  FirebaseAuthError,
  createDocsJsonHandler,
  docsSeedScript,
  injectDocsScript,
  swaggerShellHtml,
  Public,
  PUBLIC_METADATA_KEY,
  isPublicContext,
  Roles,
  ROLES_METADATA_KEY,
  requiredRoles,
  createCredentialGuard,
  getIdentity,
  IDENTITY_CONTEXT_KEY,
  scopeRoles,
} from "@foundation/mod-root.ts";
export type {
  LogLevel,
  RequestContext,
  TokenPayload,
  TokenAuthConfig,
  MintUiConfig,
  FetchHandler,
  FirebaseClaims,
  FirebaseVerifier,
  FirebaseVerifierOptions,
  DocsJsonHandlerOptions,
  CredentialGuardConfig,
  DanetGuard,
  Identity,
} from "@foundation/mod-root.ts";

export function safeStart(cb: () => Promise<void>): Promise<void> | undefined {
  if (import.meta.main) {
    return cb();
  }
}
