// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { SurveyDto } from "@/src/checkout/dto/survey.ts";
import type { ThanksDto } from "@/src/checkout/dto/thanks.ts";
import { Feedback } from "@/src/checkout/domain/business/feedback/mod.ts";

// Coordinator for [REQ] feedback.collect(SurveyDto): ThanksDto.
export async function collect(input: SurveyDto): Promise<ThanksDto> {

  // core — pure business logic, no I/O
  const out = collectCore(input);

  return out.result;
}

// Pure business logic for feedback.collect — no I/O. Takes the
// request input; returns the result.
function collectCore(input: SurveyDto): { result: ThanksDto } {
  const _feedback = new Feedback();
  return { result: { thanked: true } };
}
