// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Ticket } from "./mod.ts";

Deno.test("Ticket.toDto", () => {
  // TODO: test toDto
});
