// Generated by rune manifest from src/lists/lists.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { List } from "./mod.ts";

Deno.test("List.fill", () => {
  // TODO: test fill
});

Deno.test("List.save", () => {
  // TODO: test save
});

Deno.test("List.toDto", () => {
  // TODO: test toDto
});

Deno.test("List.load", () => {
  // TODO: test load
});

Deno.test("List.append", () => {
  // TODO: test append
});
