// Generated by rune manifest from spec/runes/notes.rune:25.
// Edit the body. Re-running manifest will not overwrite this file.

/** whether the note has been archived */
// rune declares: [TYP] archived: boolean
export type Archived = boolean;
