// Generated by rune manifest from spec/runes/notes.rune:23.
// Edit the body. Re-running manifest will not overwrite this file.

/** the note body text */
// rune declares: [TYP] body: string
export type Body = string;
