// Generated by rune manifest from spec/runes/notes.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * input to create a new note
 * @internal
 */
// rune declares: [DTO] CreateNoteDto: body
export class CreateNoteDto {
  /** the note body text */
  // rune declares: [TYP] body: string
  @ApiProperty({ description: "the note body text" })
  @IsString()
  body!: string;
}
