// Generated by rune manifest from spec/runes/notes.rune:21.
// Edit the body. Re-running manifest will not overwrite this file.

/** a unique note identifier */
// rune declares: [TYP] id: string
export type Id = string;
