// Generated by rune manifest from spec/runes/notes.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsBoolean, IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * a persisted note record
 * @internal
 */
// rune declares: [DTO] NoteDto: id, body, archived
export class NoteDto {
  /** a unique note identifier */
  // rune declares: [TYP] id: string
  @ApiProperty({ description: "a unique note identifier" })
  @IsString()
  id!: string;

  /** the note body text */
  // rune declares: [TYP] body: string
  @ApiProperty({ description: "the note body text" })
  @IsString()
  body!: string;

  /** whether the note has been archived */
  // rune declares: [TYP] archived: boolean
  @ApiProperty({ description: "whether the note has been archived" })
  @IsBoolean()
  archived!: boolean;
}
