// Generated by rune manifest from spec/runes/notes.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * a reference to an existing note
 * @internal
 */
// rune declares: [DTO] NoteRefDto: id
export class NoteRefDto {
  /** a unique note identifier */
  // rune declares: [TYP] id: string
  @ApiProperty({ description: "a unique note identifier" })
  @IsString()
  id!: string;
}
