// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// whether delivery completed
// rune declares: [TYP] delivered: boolean
export type Delivered = boolean;
