// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsBoolean } from "class-validator";

// delivery confirmation
export class DoneDto {
  @IsBoolean()
  delivered!: boolean;
}
