// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// the payment to fulfill
export class FulfillDto {
  @IsString()
  paymentId!: string;
}
