// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a thing to buy
// rune declares: [TYP] item: string
export type Item = string;
