// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// the ticket to pay
export class PayDto {
  @IsString()
  ticketId!: string;
}
