// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a payment identifier
// rune declares: [TYP] paymentId: string
export type PaymentId = string;
