// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// a settled payment
export class PaymentDto {
  @IsString()
  paymentId!: string;
}
