// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// a 1-5 satisfaction score
// rune declares: [TYP] rating: number
export type Rating = number;
