// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// what to buy and who buys it
export class StartDto {
  @IsString()
  item!: string;

  @IsString()
  memberId!: string;
}
