// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsNumber } from "class-validator";

// feedback on the purchase
export class SurveyDto {
  @IsNumber()
  rating!: number;
}
