// Generated by rune manifest from checkout.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsBoolean } from "class-validator";

// survey acknowledgement
export class ThanksDto {
  @IsBoolean()
  thanked!: boolean;
}
